import logging

import ibetin_liveline_v25_fast_cache as v25

logger = logging.getLogger(__name__)
v23 = v25.v23
API_PATH = v23.liveline.LIVELINE_API_PATH


def _page_v30() -> str:
    html = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<meta http-equiv="Cache-Control" content="no-store">
<meta name="referrer" content="no-referrer">
<title>IBETIN Live Cricket</title>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>
:root{--bg:#eef3f8;--navy:#071a34;--blue:#0b5cb4;--gold:#f6c84b;--ink:#102c4b;--muted:#7b8ea2;--card:#fff;--live:#ef4763;--green:#0c9a68;--shadow:0 8px 24px rgba(5,34,69,.08)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Inter,Arial,sans-serif;background:var(--bg);color:var(--ink);-webkit-tap-highlight-color:transparent}body{padding-bottom:calc(145px + env(safe-area-inset-bottom));scroll-padding-bottom:calc(145px + env(safe-area-inset-bottom))}
.shell{max-width:760px;margin:auto}.top{position:sticky;top:0;z-index:30;background:linear-gradient(118deg,#041326,#0a315f 74%,#0b4d8e);color:#fff;padding:14px 16px 12px;box-shadow:0 5px 18px rgba(4,23,47,.18)}
.toprow{display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:11px}.mark{width:46px;height:46px;border-radius:14px;background:var(--gold);color:#17314e;display:grid;place-items:center;font-weight:1000;font-size:23px}.brand b{display:block;font-size:22px;letter-spacing:1px}.brand span{display:block;font-size:11px;color:#c7d8eb;margin-top:2px}.liveDot{font-size:11px;font-weight:900;padding:7px 10px;border-radius:999px;background:rgba(14,160,105,.19);border:1px solid rgba(81,220,162,.3);color:#fff}
.tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:14px}.tab{height:48px;border:0;border-radius:13px;background:rgba(255,255,255,.08);color:#c5d6e9;font-size:14px;font-weight:900}.tab.on{background:#fff;color:#0a315f}
.main{padding:16px 16px calc(145px + env(safe-area-inset-bottom))}.tools{display:flex;gap:10px;margin-bottom:8px}.search{flex:1;height:52px;border:1px solid #e7edf3;border-radius:15px;background:#fff;padding:0 16px;font-size:15px;outline:none;box-shadow:var(--shadow)}.refresh{width:52px;border:1px solid #e7edf3;border-radius:15px;background:#fff;color:#0a4f98;font-size:23px;box-shadow:var(--shadow)}.status{font-size:12px;color:#8293a5;margin:10px 3px 12px}.list{display:grid;gap:12px}.league{font-size:14px;font-weight:900;color:#46627f;margin:8px 3px 1px}
.match{background:#fff;border-radius:18px;overflow:hidden;box-shadow:var(--shadow);border-left:4px solid #dbe5ef;cursor:pointer}.match.live{border-left-color:var(--live)}.mh{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:13px 14px 5px}.fmt{font-size:11px;color:#8697a8;font-weight:800}.badge{font-size:10px;font-weight:1000;padding:6px 8px;border-radius:999px;background:#eef4fb;color:#51718f}.badge.live{background:#fff0f2;color:#d72d45}
.team{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:10px 14px}.miniMark,.teamMark{border-radius:50%;display:grid;place-items:center;background:#edf4fb;color:#0b4f94;font-weight:1000;border:1px solid #dbe7f2;overflow:hidden}.miniMark{width:34px;height:34px;font-size:10px}.teamMark{width:40px;height:40px;font-size:11px}.miniMark img,.teamMark img{width:100%;height:100%;object-fit:cover}.tn{font-size:17px;font-weight:1000}.ta{font-size:10px;color:#96a5b4;margin-top:2px}.sc{text-align:right;font-size:27px;font-weight:1000;color:#083f7f;letter-spacing:-.5px}.si{text-align:right;font-size:11px;color:#8b9bad;margin-top:2px}
.oddsRow{display:grid;grid-template-columns:auto 1fr 1fr;gap:7px;align-items:center;padding:9px 14px;border-top:1px solid #f0f3f6;background:#fbfdff}.oddsTitle{font-size:9px;font-weight:1000;color:#7d91a5;letter-spacing:.35px;white-space:nowrap}.oddBox{min-width:0;background:#edf5fd;border:1px solid #dbe9f6;border-radius:10px;padding:8px 9px;display:flex;align-items:center;justify-content:space-between;gap:6px}.oddLabel{font-size:9px;font-weight:800;color:#5e7891;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.oddValue{font-size:13px;font-weight:1000;color:#0a579e;white-space:nowrap}.foot{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:11px 14px;border-top:1px solid #f0f3f6;font-size:12px;color:#6f8499}
.empty,.err,.loading{background:#fff;border-radius:16px;padding:30px 16px;text-align:center;color:#73879a;font-size:13px;box-shadow:var(--shadow)}.spin{width:24px;height:24px;border:3px solid #dce5ed;border-top-color:#0b5cb4;border-radius:50%;animation:s .7s linear infinite;margin:0 auto 10px}@keyframes s{to{transform:rotate(360deg)}}
.detail{display:none;padding:16px 16px calc(175px + env(safe-area-inset-bottom))}.back{height:44px;border:0;border-radius:13px;background:#fff;color:#24578d;font-size:14px;font-weight:1000;padding:0 14px;box-shadow:0 2px 10px rgba(6,37,70,.04)}.scorehero{margin-top:10px;border-radius:20px;background:#fff;overflow:hidden;border:1px solid #e6edf4;box-shadow:var(--shadow)}.scoretop{padding:12px 14px;border-bottom:1px solid #edf1f5;font-size:11px;color:#6f8397;display:flex;justify-content:space-between;gap:10px}.scoremain{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:10px;padding:20px 14px}.side.right{text-align:right}.teamIdentity{display:flex;align-items:center;gap:8px;margin-bottom:6px}.side.right .teamIdentity{justify-content:flex-end}.sname{font-size:13px;font-weight:1000;color:#294662}.sval{font-size:31px;font-weight:1000;color:#083f7f;margin-top:4px;letter-spacing:-.6px}.vs{width:38px;height:38px;border-radius:50%;background:#fff5cf;color:#765700;display:grid;place-items:center;font-size:10px;font-weight:1000}.report{padding:12px 14px;background:#fbfdff;border-top:1px solid #edf1f5;font-size:11px;color:#637b91}
.quickMarket{margin-top:11px;background:#fff;border-radius:16px;padding:13px;box-shadow:var(--shadow);border:1px solid #e6edf4}.quickHead{display:flex;align-items:center;justify-content:space-between;margin-bottom:9px}.quickHead b{font-size:13px}.quickHead span{font-size:9px;color:#6c8297;font-weight:900}.quickOdds{display:grid;grid-template-columns:1fr 1fr;gap:8px}.quickOdd{background:#edf5fd;border:1px solid #dbe9f6;border-radius:12px;padding:10px}.quickOdd small{display:block;color:#6d8297;font-size:9px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.quickOdd strong{display:block;color:#084f94;font-size:20px;margin-top:3px}.sessionTitle{font-size:10px;font-weight:1000;color:#73889c;margin:12px 0 6px}.sessionGrid{display:grid;gap:7px}.sessionCard{background:#f8fafc;border:1px solid #e7edf3;border-radius:11px;padding:9px}.sessionCard b{font-size:10px;color:#284d70}.sessionVals{display:flex;gap:8px;flex-wrap:wrap;margin-top:5px;font-size:10px;color:#637b92}.sessionVals strong{color:#0a579e}.quickLoading{font-size:11px;color:#758a9f;padding:4px 0}
.chaseBox{margin-top:9px;background:linear-gradient(135deg,#edf6ff,#f8fbff);border:1px solid #d8e9f8;border-radius:12px;padding:11px 12px}.chaseBox b{display:block;font-size:14px;color:#164a79}.chaseBox span{font-size:10px;color:#6f8498}.lastSix{display:flex;align-items:center;gap:6px;overflow:auto;margin-top:10px;scrollbar-width:none}.lastSix::-webkit-scrollbar{display:none}.lastSixTitle{font-size:9px;font-weight:1000;color:#8194a7;letter-spacing:.4px;margin-right:2px;white-space:nowrap}.ballChip{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#eaf1f8;color:#294d70;font-size:10px;font-weight:1000;flex:none}.ballChip.boundary{background:#e6f4ff;color:#0968b7}.ballChip.six{background:#efe9ff;color:#6943b5}.ballChip.wicket{background:#fff0f2;color:#d02f47}.ballChip.extra{background:#fff6db;color:#856200}
.dtabs{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;margin:11px 0}.dtab{height:43px;border:1px solid #e4ebf2;border-radius:12px;background:#fff;color:#687f96;font-size:9px;font-weight:1000;padding:0 3px}.dtab.on{background:#0a315f;color:#fff;border-color:#0a315f}.panel{background:#fff;border-radius:16px;padding:13px;box-shadow:var(--shadow);margin-bottom:14px}.ptitle{margin-bottom:10px}.ptitle b{font-size:13px}.notice{background:#f7f9fb;border-radius:12px;padding:11px;font-size:11px;color:#647c92;line-height:1.5;margin-bottom:8px}.metricRow{display:flex;gap:7px;flex-wrap:wrap}.metric{display:inline-flex;gap:4px;align-items:center;background:#edf4fb;border-radius:999px;padding:7px 9px;color:#58728b;font-size:10px}.playerStrip{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.playerCard{background:#f7f9fc;border:1px solid #e8edf3;border-radius:12px;padding:10px;min-width:0}.playerRole{font-size:8px;font-weight:1000;color:#8b9caf;letter-spacing:.6px;margin-bottom:4px}.playerName{font-size:11px;font-weight:900;color:#173a5e;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.playerStat{font-size:10px;color:#617b93;margin-top:3px}
.innings{display:grid;gap:8px}.inning{border:1px solid #e7edf3;background:#f9fbfd;border-radius:12px;padding:11px}.inningTop{display:flex;align-items:center;justify-content:space-between;gap:8px}.inningTeam{font-size:12px;font-weight:900}.inningScore{font-size:18px;font-weight:1000;color:#083f7f}.inningMeta{font-size:10px;color:#8091a2;margin-top:4px}.balls{display:grid;gap:7px}.ball{background:#f8fafc;border-radius:10px;padding:9px;font-size:10px;line-height:1.45}.moreGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.moreItem{border:1px solid #e5ebf2;background:#f8fafc;border-radius:13px;padding:14px 11px;text-align:left;color:#234766;font-size:11px;font-weight:900}.moreItem span{display:block;font-size:9px;font-weight:600;color:#7d90a3;margin-top:4px}.kv{display:grid;grid-template-columns:1fr auto;gap:8px;padding:9px 0;border-bottom:1px solid #edf1f4;font-size:10px}.kv b{color:#244867}
.bottom{position:fixed;left:14px;right:14px;bottom:calc(10px + env(safe-area-inset-bottom));z-index:40;max-width:732px;margin:auto;display:grid;grid-template-columns:repeat(4,1fr);gap:4px;background:rgba(5,22,45,.98);border-radius:20px;padding:8px;box-shadow:0 12px 30px rgba(4,23,48,.25)}.bottom button{border:0;background:transparent;color:#9fb2c8;height:54px;border-radius:13px;font-size:9px;font-weight:1000}.bottom b{display:block;font-size:18px;margin-bottom:2px}.bottom .on{background:rgba(255,255,255,.1);color:#fff}
@media(min-width:620px){.list{grid-template-columns:1fr 1fr}.league{grid-column:1/-1}}@media(max-width:390px){.brand b{font-size:20px}.mark{width:42px;height:42px}.tab{font-size:12px}.tn{font-size:15px}.sc{font-size:24px}.sval{font-size:27px}.playerStrip{grid-template-columns:1fr}.oddsRow{grid-template-columns:1fr 1fr}.oddsTitle{grid-column:1/-1}.dtab{font-size:8px}.quickOdds{grid-template-columns:1fr 1fr}}
</style><link rel="icon" href="data:">
</head>
<body>
<div class="shell">
<header class="top"><div class="toprow"><div class="brand"><div class="mark">I</div><div><b>IBETIN</b><span>LIVE CRICKET</span></div></div><div class="liveDot">● LIVE</div></div><div class="tabs"><button class="tab on" data-mode="live">● LIVE</button><button class="tab" data-mode="upcoming">UPCOMING</button><button class="tab" data-mode="results">RESULTS</button></div></header>
<main id="home" class="main"><div class="tools"><input id="search" class="search" placeholder="Search match, team or tournament"><button id="refresh" class="refresh">↻</button></div><div id="status" class="status">Loading live cricket…</div><div id="list" class="list"></div></main>
<section id="detail" class="detail"></section>
</div>
<nav class="bottom"><button class="on" data-nav="home"><b>⌂</b>HOME</button><button data-nav="live"><b style="color:#ff5b6f">●</b>LIVE</button><button data-nav="fixtures"><b>◷</b>FIXTURES</button><button data-nav="search"><b>⌕</b>SEARCH</button></nav>
<script>
'use strict';
const tg=window.Telegram&&window.Telegram.WebApp;
if(tg){try{tg.ready();tg.expand();tg.setHeaderColor('#071a34');tg.setBackgroundColor('#eef3f8')}catch(e){}}
const qs=new URLSearchParams(location.search),TOKEN=qs.get('t')||'',API_PATH='__API_PATH__';
let mode='live',allMatches=[],detailData=null,detailTab='match',refreshTimer=null,loadGeneration=0,lastHomeLoad=0;
const bhavCache=new Map(),bhavBusy=new Set();
const BHAV_TTL=10000;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const display=v=>v===null||v===undefined||v===''?'—':esc(v);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function api(params,retry=true){params.t=TOKEN;const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),7000);try{const r=await fetch(API_PATH+'?'+new URLSearchParams(params),{cache:'no-store',signal:ctrl.signal});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));return j}catch(e){if(retry&&e.name!=='AbortError'){await sleep(250);return api(params,false)}throw e}finally{clearTimeout(timer)}}
function loading(el){el.innerHTML='<div class="loading"><div class="spin"></div>Loading…</div>'}
function fmtTime(v){if(!v)return'';try{let x=v;if(typeof v==='string'&&/^\d+(\.\d+)?$/.test(v))x=Number(v)*1000;else if(typeof v==='number'&&v<1000000000000)x=v*1000;const d=new Date(x);if(Number.isNaN(d.getTime()))return'';return d.toLocaleString([],{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}catch(e){return''}}
function prettyState(v){const s=String(v||'').toLowerCase().replace(/[_-]+/g,' ').trim();if(!s)return'';if(['in play','inplay','started','live','playing'].includes(s))return'LIVE';if(['not started','scheduled','upcoming','fixture','created','confirmed'].includes(s))return'UPCOMING';if(['completed','complete','finished','result','ended','closed'].includes(s))return'FINAL';return s.replace(/\b\w/g,c=>c.toUpperCase())}
function matchKey(m){return String(m?.roanuzMatchKey||m?.id||'')}
function league(m){return m?.league?.name||'Cricket'}
function initials(t){const n=String(t?.name||t?.abbr||'TM').trim(),p=n.split(/\s+/).filter(Boolean);return (p.length>1?(p[0][0]+p[1][0]):n.slice(0,2)).toUpperCase()}
function imageUrl(t){return t?.logo||t?.logoUrl||t?.image||t?.imageUrl||t?.flag||t?.flagUrl||''}
function miniMark(t){const u=imageUrl(t),i=esc(initials(t));return u?`<span class="miniMark"><img src="${esc(u)}" alt="" onerror="this.parentElement.textContent='${i}'"></span>`:`<span class="miniMark">${i}</span>`}
function teamMark(t){const u=imageUrl(t),i=esc(initials(t));return u?`<span class="teamMark"><img src="${esc(u)}" alt="" onerror="this.parentElement.textContent='${i}'"></span>`:`<span class="teamMark">${i}</span>`}
function teamRow(t,s,i){return `<div class="team">${miniMark(t)}<div><div class="tn">${esc(t?.name||t?.abbr||'Team')}</div><div class="ta">${esc(t?.abbr||'')}</div></div><div><div class="sc">${display(s)}</div><div class="si">${esc(i||'')}</div></div></div>`}
function entries(j){return Array.isArray(j?.entries)?j.entries:[]}
function values(e){return Array.isArray(e?.values)?e.values.filter(v=>v&&v.odd!==undefined&&v.odd!==null):[]}
function findMatchMarket(j){const es=entries(j);return es.find(e=>/match|winner|moneyline/i.test(String(e?.market||''))&&values(e).length>=2)||es.find(e=>values(e).length>=2)||null}
function sessionMarkets(j,main){return entries(j).filter(e=>e!==main&&values(e).length>=2&&/over|session|runs|line|total|fancy|innings/i.test(String(e?.market||''))).slice(0,3)}
function homeOddsHtml(m){if(mode!=='live')return'';const c=bhavCache.get(matchKey(m));if(!c?.data)return'';const market=findMatchMarket(c.data);if(!market)return'';const vs=values(market).slice(0,2);return `<div class="oddsRow"><span class="oddsTitle">MATCH ODDS</span>${vs.map(x=>`<div class="oddBox"><span class="oddLabel">${esc(x.label||'Selection')}</span><span class="oddValue">${esc(x.odd)}</span></div>`).join('')}</div>`}
function card(m){const live=mode==='live',label=live?'● LIVE':mode==='upcoming'?(fmtTime(m.startTime)||'UPCOMING'):(prettyState(m.state)||'FINAL');return `<article class="match ${live?'live':''}" data-key="${esc(matchKey(m))}"><div class="mh"><div class="fmt">${esc(m.format||'CRICKET')} · ${esc(league(m))}</div><span class="badge ${live?'live':''}">${esc(label)}</span></div>${teamRow(m.home,m.homeScore,m.homeInfo)}${teamRow(m.away,m.awayScore,m.awayInfo)}${homeOddsHtml(m)}<div class="foot"><span>${esc(m.report||prettyState(m.state)||fmtTime(m.startTime)||'Tap for details')}</span><b>›</b></div></article>`}
function render(){const q=(document.getElementById('search').value||'').trim().toLowerCase(),rows=allMatches.filter(m=>!q||[m.home?.name,m.away?.name,league(m),m.format].join(' ').toLowerCase().includes(q)),list=document.getElementById('list');if(!rows.length){list.innerHTML='<div class="empty">No matching cricket matches found.</div>';return}let last='';list.innerHTML=rows.map(m=>{const l=league(m),h=l!==last?`<div class="league">${esc(l)}</div>`:'';last=l;return h+card(m)}).join('');list.querySelectorAll('.match').forEach(el=>el.onclick=()=>openMatch(el.dataset.key));if(mode==='live')setTimeout(()=>rows.slice(0,6).forEach(m=>getBhav(matchKey(m))),120)}
function mergeScore(base,fresh){if(!base||!fresh)return base;return {...base,home:fresh.home||base.home,away:fresh.away||base.away,homeScore:fresh.homeScore||base.homeScore,homeInfo:fresh.homeInfo||base.homeInfo,awayScore:fresh.awayScore||base.awayScore,awayInfo:fresh.awayInfo||base.awayInfo,report:fresh.report||base.report,state:fresh.state||base.state}}
async function hydrateScore(m){const key=matchKey(m);if(!key)return;try{const j=await api({action:'score',key});const i=allMatches.findIndex(x=>matchKey(x)===key);if(i>=0){allMatches[i]=mergeScore(allMatches[i],j.match||{});render()}}catch(e){}}
async function getBhav(key,force=false){if(!key)return null;const c=bhavCache.get(key);if(!force&&c&&Date.now()-c.ts<BHAV_TTL)return c.data;if(bhavBusy.has(key))return c?.data||null;bhavBusy.add(key);try{const j=await api({action:'bhav',matchId:key},false);bhavCache.set(key,{ts:Date.now(),data:j});if(mode==='live'&&document.getElementById('home').style.display!=='none')render();return j}catch(e){bhavCache.set(key,{ts:Date.now(),data:null});return null}finally{bhavBusy.delete(key)}}
async function load(nextMode=mode,force=false){mode=nextMode;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));const gen=++loadGeneration,list=document.getElementById('list');if(force||!allMatches.length)loading(list);document.getElementById('status').textContent='Updating '+mode+' matches…';try{const j=await api({action:'matches',mode});if(gen!==loadGeneration)return;allMatches=j.matches||[];render();lastHomeLoad=Date.now();const stamp=j.generatedAt?new Date(j.generatedAt):new Date();document.getElementById('status').textContent=`${allMatches.length} ${mode==='live'?'live ':''}matches · Updated ${stamp.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;if(mode==='live'){allMatches.slice(0,6).forEach(hydrateScore);setTimeout(()=>allMatches.slice(0,6).forEach(hydrateScore),1600)}}catch(e){if(gen!==loadGeneration)return;if(allMatches.length){document.getElementById('status').textContent='Showing last update · Refresh to retry'}else list.innerHTML='<div class="err">Live cricket is temporarily unavailable.<br><br><button class="back" onclick="load(mode,true)">RETRY</button></div>'}if(refreshTimer)clearInterval(refreshTimer);if(mode==='live')refreshTimer=setInterval(()=>{if(!document.hidden&&document.getElementById('home').style.display!=='none')load('live')},30000)}
function showTelegramBack(on){if(!tg?.BackButton)return;try{if(on){tg.BackButton.show();tg.BackButton.onClick(backHome)}else{tg.BackButton.offClick(backHome);tg.BackButton.hide()}}catch(e){}}
async function openMatch(key){if(!key)return;document.getElementById('home').style.display='none';const d=document.getElementById('detail');d.style.display='block';loading(d);showTelegramBack(true);try{const j=await api({action:'match',id:key});detailData=j.detail||{};detailTab='match';drawDetail();getBhav(key).then(x=>{if(document.getElementById('quickMarket'))renderQuickMarket(x);if(detailTab==='bhav')drawPanel()})}catch(e){d.innerHTML=`<button class="back" onclick="backHome()">← BACK</button><div class="err">Unable to load match details.<br><br><button class="back" onclick="openMatch('${esc(key)}')">RETRY</button></div>`}}
function backHome(){document.getElementById('detail').style.display='none';document.getElementById('home').style.display='block';detailData=null;showTelegramBack(false);window.scrollTo({top:0,behavior:'smooth'});if(Date.now()-lastHomeLoad>15000)load(mode)}
function targetRuns(t){if(!t||typeof t!=='object')return null;for(const k of ['runs','target','score','target_runs','targetRuns']){const v=Number(t[k]);if(Number.isFinite(v)&&v>0)return v}return null}
function targetBalls(t){if(!t||typeof t!=='object')return null;for(const k of ['balls','balls_remaining','ballsRemaining']){const v=Number(t[k]);if(Number.isFinite(v)&&v>=0)return v}return null}
function scoreRuns(s){const m=String(s||'').match(/^\s*(\d+)/);return m?Number(m[1]):null}
function scoreOvers(info){const m=String(info||'').match(/(\d+)(?:\.(\d+))?/);if(!m)return null;return Number(m[1])*6+Number(m[2]||0)}
function chaseInfo(target,m){const tr=targetRuns(target);if(!tr)return'';const h=scoreRuns(m.homeScore),a=scoreRuns(m.awayScore),hb=scoreOvers(m.homeInfo),ab=scoreOvers(m.awayInfo);let battingRuns=null,ballsUsed=null,team='Chasing side';if(ab!==null&&(hb===null||ab>=hb)){battingRuns=a;ballsUsed=ab;team=m.away?.name||team}else if(hb!==null){battingRuns=h;ballsUsed=hb;team=m.home?.name||team}const need=battingRuns===null?null:Math.max(0,tr-battingRuns);let balls=targetBalls(target);if(balls===null&&ballsUsed!==null)balls=Math.max(0,120-ballsUsed);if(need===null)return `<div class="chaseBox"><b>Target ${tr}</b></div>`;const rrr=balls>0?((need*6)/balls).toFixed(2):null;return `<div class="chaseBox"><b>${esc(team)} need ${need}${balls!==null?' from '+balls+' balls':''}</b><span>Target ${tr}${rrr?' · RRR '+rrr:''}</span></div>`}
function ballOutcome(e){const s=String(e?.commentary||e?.comment||e?.description||e?.text||'').toLowerCase();if(/six|6 runs|6 run/.test(s))return['6','six'];if(/four|4 runs|4 run/.test(s))return['4','boundary'];if(/wicket|out\b|bowled|caught|lbw|run out/.test(s))return['W','wicket'];if(/no.?ball/.test(s))return['NB','extra'];if(/wide/.test(s))return['WD','extra'];const m=s.match(/\b([0-3]) runs?\b/);if(m)return[m[1],''];if(/dot ball|no run/.test(s))return['•',''];return['•','']}
function lastSixHtml(rows){const a=(Array.isArray(rows)?rows:[]).slice(-6);if(!a.length)return'';return `<div class="lastSix"><span class="lastSixTitle">LAST 6</span>${a.map(e=>{const o=ballOutcome(e);return `<span class="ballChip ${o[1]}">${o[0]}</span>`}).join('')}</div>`}
function rateValue(v){if(v===null||v===undefined||v==='')return'';if(typeof v==='number'||typeof v==='string')return String(v);if(typeof v==='object'){for(const k of ['current','value','rate','run_rate','runRate'])if(v[k]!==undefined&&v[k]!==null)return String(v[k])}return''}
function normKey(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function deepFind(root,aliases,depth=0,seen){if(root===null||root===undefined||depth>5||typeof root!=='object')return null;seen=seen||new Set();if(seen.has(root))return null;seen.add(root);const wanted=new Set(aliases.map(normKey));for(const [k,v] of Object.entries(root))if(wanted.has(normKey(k))&&v!==null&&v!==undefined)return v;for(const v of Object.values(root)){if(v&&typeof v==='object'){const found=deepFind(v,aliases,depth+1,seen);if(found!==null&&found!==undefined)return found}}return null}
function playerInfo(v){if(v===null||v===undefined)return null;if(typeof v==='string')return{name:v,stat:''};if(typeof v!=='object')return null;const p=(v.player&&typeof v.player==='object')?v.player:v,name=p.name||p.full_name||p.fullName||p.short_name||p.shortName||p.player_name||p.playerName||v.name||'';if(!name)return null;const runs=v.runs??v.score??p.runs??p.score,balls=v.balls??v.balls_faced??v.ballsFaced??p.balls??p.balls_faced,wickets=v.wickets??p.wickets,overs=v.overs??p.overs;let stat='';if(runs!==undefined&&runs!==null)stat=String(runs)+(balls!==undefined&&balls!==null?' ('+balls+')':'');else if(wickets!==undefined&&wickets!==null)stat=String(wickets)+' wkts'+(overs!==undefined&&overs!==null?' · '+overs+' ov':'');return{name:String(name),stat}}
function currentPlayersHtml(detail){const root=detail?.inplayData||{},striker=playerInfo(deepFind(root,['striker','current_striker','currentBatsman','current_batsman','batsman','batter','on_strike'])),bowler=playerInfo(deepFind(root,['bowler','current_bowler','currentBowler','bowling','currentBowling']));if(!striker&&!bowler)return'';return `<div class="playerStrip">${striker?`<div class="playerCard"><div class="playerRole">AT CREASE</div><div class="playerName">${esc(striker.name)}</div>${striker.stat?`<div class="playerStat">${esc(striker.stat)}</div>`:''}</div>`:''}${bowler?`<div class="playerCard"><div class="playerRole">BOWLER</div><div class="playerName">${esc(bowler.name)}</div>${bowler.stat?`<div class="playerStat">${esc(bowler.stat)}</div>`:''}</div>`:''}</div>`}
function quickMarketHtml(j){if(!j)return'';const main=findMatchMarket(j);if(!main)return'';const mv=values(main).slice(0,2),sessions=sessionMarkets(j,main);return `<div class="quickHead"><b>LIVE BHAV</b><span>LIVE MARKET</span></div><div class="quickOdds">${mv.map(v=>`<div class="quickOdd"><small>${esc(v.label||'Selection')}</small><strong>${esc(v.odd)}</strong></div>`).join('')}</div>${sessions.length?`<div class="sessionTitle">SESSION MARKETS</div><div class="sessionGrid">${sessions.map(e=>`<div class="sessionCard"><b>${esc(e.market||'Session')}</b><div class="sessionVals">${values(e).slice(0,3).map(v=>`<span>${esc(v.label||'Line')} <strong>${esc(v.odd)}</strong></span>`).join('')}</div></div>`).join('')}</div>`:''}`}
function renderQuickMarket(j){const el=document.getElementById('quickMarket');if(!el)return;const h=quickMarketHtml(j);if(h){el.style.display='block';el.innerHTML=h}else{el.style.display='none';el.innerHTML=''}}
function tabsHtml(){const moreOn=['more','graphs','stats','info'].includes(detailTab);return [['match','MATCH'],['bhav','BHAV'],['scorecard','SCORECARD'],['balls','BALLS'],['more','MORE']].map(([k,l])=>`<button class="dtab ${(detailTab===k||(k==='more'&&moreOn))?'on':''}" data-tab="${k}">${l}</button>`).join('')}
function drawDetail(){const d=document.getElementById('detail'),m=detailData?.match||{},cached=bhavCache.get(matchKey(m))?.data||null;d.innerHTML=`<button class="back" onclick="backHome()">← BACK</button><div class="scorehero"><div class="scoretop"><span>${esc(league(m))} · ${esc(m.format||'')}</span><span>${esc(prettyState(m.state)||'')}</span></div><div class="scoremain"><div class="side"><div class="teamIdentity">${teamMark(m.home)}</div><div class="sname">${esc(m.home?.name||'Home')}</div><div class="sval">${display(m.homeScore)}</div><div class="ta">${esc(m.homeInfo||'')}</div></div><div class="vs">VS</div><div class="side right"><div class="teamIdentity">${teamMark(m.away)}</div><div class="sname">${esc(m.away?.name||'Away')}</div><div class="sval">${display(m.awayScore)}</div><div class="ta">${esc(m.awayInfo||'')}</div></div></div><div class="report">${esc(m.report||prettyState(m.state)||'')}${detailData?.roanuz?.target?chaseInfo(detailData.roanuz.target,m):''}${lastSixHtml(detailData?.timeline||[])}</div></div><div id="quickMarket" class="quickMarket" style="${cached?'':'display:block'}">${cached?quickMarketHtml(cached):'<div class="quickLoading">Loading live BHAV…</div>'}</div><div class="dtabs">${tabsHtml()}</div><div id="panel" class="panel"></div>`;d.querySelectorAll('.dtab').forEach(b=>b.onclick=()=>{detailTab=b.dataset.tab;drawDetail()});drawPanel()}
function inningsRows(detail){if(Array.isArray(detail?.statistics)&&detail.statistics.length)return detail.statistics;if(Array.isArray(detail?.innings))return detail.innings;return[]}
function inningScore(row){if(!row||typeof row!=='object')return'';if(row.score_str)return String(row.score_str).split(' in ')[0];const s=row.score&&typeof row.score==='object'?row.score:{},runs=s.runs??row.runs??row.score,w=s.wickets??row.wickets;if(runs===undefined||runs===null||typeof runs==='object')return'';return String(runs)+(w!==undefined&&w!==null?'/'+w:'')}
function inningOvers(row){if(!row||typeof row!=='object')return'';let v=row.overs??row.over??(row.score&&typeof row.score==='object'?row.score.overs:null);if(Array.isArray(v))return v.length>1?`${v[0]}.${v[1]} ov`:'';return v!==undefined&&v!==null&&v!==''?String(v)+(String(v).toLowerCase().includes('ov')?'':' ov'):''}
function inningName(row,i){if(!row||typeof row!=='object')return `Innings ${i+1}`;const t=row.team||row.batting_team||row.battingTeam||row.team_name||row.name;if(typeof t==='string'&&t)return t;if(t&&typeof t==='object')return t.name||t.short_name||t.shortName||`Innings ${i+1}`;return `Innings ${i+1}`}
function scorecardHtml(detail){const rows=inningsRows(detail);if(!rows.length)return'<div class="notice">Scorecard will appear as soon as innings data is available.</div>';return `<div class="innings">${rows.map((r,i)=>`<div class="inning"><div class="inningTop"><div class="inningTeam">${esc(inningName(r,i))}</div><div class="inningScore">${esc(inningScore(r)||'—')}</div></div><div class="inningMeta">${esc(inningOvers(r))}</div></div>`).join('')}</div>`}
function ballsHtml(detail){const a=Array.isArray(detail?.timeline)?detail.timeline:[];if(!a.length)return'<div class="notice">Ball-by-ball will appear with the next live update.</div>';return `<div class="balls">${a.slice().reverse().slice(0,60).map((e,i)=>`<div class="ball"><b>${esc(e.over||e.ball||('#'+(i+1)))}</b><br>${esc(e.commentary||e.comment||e.description||e.text||'Delivery update')}</div>`).join('')}</div>`}
function ptitle(t){return `<div class="ptitle"><b>${esc(t)}</b></div>`}
function fullBhavHtml(j){const es=entries(j);if(!es.length)return'<div class="notice">Live BHAV is not available for this match right now.</div>';return es.map(e=>`<div class="notice"><b>${esc(e.market||'Market')}</b><br>${values(e).map(v=>`${esc(v.label||'Selection')} <b>${esc(v.odd)}</b>`).join(' · ')}</div>`).join('')}
function drawPanel(){const p=document.getElementById('panel'),detail=detailData||{},m=detail.match||{};if(detailTab==='match'){const rr=rateValue(detail.roanuz?.runRate);p.innerHTML=ptitle('MATCH SNAPSHOT')+`<div class="notice">${rr?`<div class="metricRow"><span class="metric">CRR <b>${esc(rr)}</b></span></div>`:''}${currentPlayersHtml(detail)}${lastSixHtml(detail.timeline||[])}</div>`}else if(detailTab==='scorecard'){p.innerHTML=ptitle('SCORECARD')+scorecardHtml(detail)}else if(detailTab==='balls'){p.innerHTML=ptitle('BALL-BY-BALL')+ballsHtml(detail)}else if(detailTab==='more'){p.innerHTML=ptitle('MORE')+'<div class="moreGrid"><button class="moreItem" data-more="graphs">GRAPHS<span>Match trends</span></button><button class="moreItem" data-more="stats">STATS<span>Match numbers</span></button><button class="moreItem" data-more="info">INFO<span>Venue and match details</span></button></div>';p.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>{detailTab=b.dataset.more;drawDetail()})}else if(detailTab==='bhav'){const key=matchKey(m),cached=bhavCache.get(key)?.data||null;p.innerHTML=ptitle('LIVE BHAV')+(cached?fullBhavHtml(cached):'<div class="loading"><div class="spin"></div>Loading…</div>');getBhav(key).then(j=>{if(detailTab==='bhav'&&document.getElementById('panel'))document.getElementById('panel').innerHTML=ptitle('LIVE BHAV')+fullBhavHtml(j)})}else if(detailTab==='graphs'){p.innerHTML=ptitle('MATCH TRENDS')+'<div class="notice">Trend data is loading…</div>';api({action:'graphs',key:matchKey(m)}).then(j=>{const g=j.graphs||{},items=Object.entries(g).slice(0,8);p.innerHTML=ptitle('MATCH TRENDS')+(items.length?items.map(([k,v])=>`<div class="kv"><span>${esc(k.replace(/_/g,' '))}</span><b>${esc(typeof v==='number'||typeof v==='string'?v:'Available')}</b></div>`).join(''):'<div class="notice">No trend data is available yet.</div>')}).catch(()=>p.innerHTML=ptitle('MATCH TRENDS')+'<div class="notice">Trend data is temporarily unavailable.</div>')}else if(detailTab==='stats'){p.innerHTML=ptitle('MATCH STATS')+scorecardHtml(detail)}else{const venue=detail.venue||{},items=[['Venue',venue.name],['City',venue.city],['Format',m.format],['Status',prettyState(m.state)]].filter(x=>x[1]);p.innerHTML=ptitle('MATCH INFO')+(items.length?items.map(x=>`<div class="kv"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join(''):'<div class="notice">Match information will appear here when available.</div>')}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{allMatches=[];load(b.dataset.mode,true)});
document.getElementById('refresh').onclick=()=>load(mode,true);
document.getElementById('search').oninput=render;
document.querySelector('.bottom').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('on',x===b));const nav=b.dataset.nav;if(nav==='home'||nav==='live'){backHome();if(mode!=='live'||Date.now()-lastHomeLoad>10000){allMatches=[];load('live',true)}}else if(nav==='fixtures'){backHome();allMatches=[];load('upcoming',true)}else{backHome();setTimeout(()=>document.getElementById('search').focus(),100)}};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&mode==='live'&&document.getElementById('home').style.display!=='none'&&Date.now()-lastHomeLoad>15000)load('live')});
window.addEventListener('unhandledrejection',e=>console.error('IBETIN UI promise error',e.reason));
window.addEventListener('error',e=>console.error('IBETIN UI error',e.message));
load('live',true);
</script>
</body>
</html>'''
    return html.replace('__API_PATH__', API_PATH)


v23._page = _page_v30
v23.liveline._page = _page_v30


def _self_test() -> None:
    page = _page_v30()
    checks = {
        'single_ui_owner': 'ibetin_liveline_v26' not in page and 'ibetin_liveline_v27' not in page,
        'home_tabs': 'UPCOMING' in page and 'RESULTS' in page,
        'detail_tabs': "['match','MATCH']" in page and "['bhav','BHAV']" in page and "['more','MORE']" in page,
        'inline_bhav': 'id="quickMarket"' in page and 'LIVE BHAV' in page and 'SESSION MARKETS' in page,
        'shared_bhav_cache': 'bhavCache' in page and 'BHAV_TTL=10000' in page and 'getBhav' in page,
        'main_odds': 'MATCH ODDS' in page and 'homeOddsHtml' in page,
        'no_provider_internals': 'ROANUZ V5 · PRIMARY DATA' not in page and 'HIGHLIGHTLY FALLBACK' not in page,
        'no_raw_json_ui': 'JSON.stringify' not in page,
        'scope_safe': 'detailData?.roanuz?.target' in page,
        'fast_score_hydrate': "action:'score'" in page,
        'safe_bottom_spacing': 'calc(175px + env(safe-area-inset-bottom))' in page,
        'telegram_back': 'tg.BackButton' in page,
        'friendly_errors': 'Unable to load match details.' in page,
    }
    live_matches = 0
    detail_ok = False
    source = ''
    try:
        rows, source = v25._fast_matches_cached('live')
        live_matches = len(rows or [])
        if rows:
            key = str(rows[0].get('roanuzMatchKey') or rows[0].get('id') or '')
            if key:
                detail, _ = v25._match_detail_cached(key)
                detail_ok = isinstance(detail, dict) and isinstance(detail.get('match'), dict)
    except Exception as exc:
        logger.warning('IBETIN V30 runtime self-test provider probe skipped: %s', str(exc)[:160])
    ok = all(checks.values()) and (detail_ok or live_matches == 0)
    (logger.info if ok else logger.error)(
        'IBETIN V30 unified self-test %s checks=%s live_matches=%s source=%s detail_ok=%s',
        'PASS' if ok else 'FAILED', checks, live_matches, source, detail_ok,
    )
    if not ok:
        raise RuntimeError(f'V30 unified UI self-test failed: {checks}')


_self_test()
logger.info('IBETIN V30 installed: inline BHAV + session markets + full BHAV tab over frozen V25 fast feed/cache')

app = v25.app

if __name__ == '__main__':
    app.base.ibetin_start.main()
