import os
from urllib.parse import urlencode

import ibetin_liveline_trial as liveline


def _light_admin_url() -> str:
    root = os.getenv("TRACKING_BASE_URL", "").strip().rstrip("/") or "https://ibetin-app-production.up.railway.app"
    return f"{root}{liveline.LIVELINE_PATH}?{urlencode({'t': liveline._token(), 'v': '20260916-v3-premium'})}"


def _light_page() -> str:
    return r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate">
<meta name="referrer" content="no-referrer">
<title>IBETIN Live Line</title>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>
:root{
  --bg:#f2f3f5;--card:#ffffff;--ink:#15171a;--muted:#7c8289;--line:#e7e9ec;
  --red:#d7192d;--red2:#f02b3f;--redSoft:#fff0f2;--green:#139b5b;--blue:#2474d8;
  --shadow:0 4px 18px rgba(21,25,30,.075);--shadow2:0 10px 28px rgba(20,25,31,.10)
}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
html,body{margin:0;min-height:100%;background:var(--bg);color:var(--ink);font-family:Inter,Arial,Helvetica,sans-serif}
body{padding:0 0 76px}button{font:inherit}.wrap{max-width:760px;margin:auto}
.topShell{position:sticky;top:0;z-index:20;background:linear-gradient(135deg,#c71025 0%,#ed273d 100%);box-shadow:0 3px 14px rgba(144,0,20,.20)}
.brandRow{height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 14px;color:#fff}.brandLeft{display:flex;align-items:center;gap:9px}.brandMark{width:34px;height:34px;border-radius:10px;background:#fff;color:var(--red);display:grid;place-items:center;font-weight:1000;font-size:18px;box-shadow:0 3px 10px rgba(0,0,0,.14)}.brandText{line-height:1}.brandText b{display:block;font-size:17px;letter-spacing:.2px}.brandText span{display:block;font-size:9px;opacity:.82;margin-top:4px;letter-spacing:.7px;text-transform:uppercase}.liveChip{display:flex;align-items:center;gap:6px;border:1px solid rgba(255,255,255,.40);background:rgba(255,255,255,.14);border-radius:999px;padding:6px 9px;font-size:9px;font-weight:900}.pulseDot{width:7px;height:7px;border-radius:50%;background:#fff;box-shadow:0 0 0 0 rgba(255,255,255,.65);animation:pulse 1.6s infinite}@keyframes pulse{70%{box-shadow:0 0 0 7px rgba(255,255,255,0)}100%{box-shadow:0 0 0 0 rgba(255,255,255,0)}}
.navCard{background:#fff}.navTabs{display:grid;grid-template-columns:repeat(3,1fr);padding:0 10px}.tab{position:relative;border:0;background:#fff;color:#7a8087;padding:12px 4px 13px;font-size:11px;font-weight:950;letter-spacing:.15px}.tab.active{color:var(--red)}.tab.active:after{content:"";position:absolute;left:26%;right:26%;bottom:0;height:3px;background:var(--red);border-radius:4px 4px 0 0}
.content,.detailWrap{padding:11px}.sectionTitle{display:flex;align-items:center;justify-content:space-between;margin:2px 1px 9px}.sectionTitle b{font-size:13px}.status{font-size:9px;color:#969ba1}.refreshBtn{border:0;background:#fff;border:1px solid var(--line);border-radius:999px;color:#646a70;font-size:9px;font-weight:850;padding:6px 9px;box-shadow:0 1px 5px rgba(20,25,30,.04)}
.list{display:grid;gap:11px}.match{position:relative;background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);overflow:hidden;cursor:pointer;transition:transform .12s ease,box-shadow .12s ease}.match:active{transform:scale(.992);box-shadow:0 2px 10px rgba(20,25,30,.07)}.match.liveCard:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--red)}
.matchHead{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 12px 9px;border-bottom:1px solid #f0f1f3}.leagueBox{min-width:0}.league{font-size:10px;font-weight:950;color:#555b62;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.format{font-size:8px;color:#9a9fa5;margin-top:3px}.badgeLive,.badgeState{flex:none;border-radius:999px;padding:5px 8px;font-size:8px;font-weight:1000;letter-spacing:.3px}.badgeLive{background:var(--red);color:#fff}.badgeState{background:#f0f2f4;color:#646a70}.badgeResult{background:#eaf8f1;color:var(--green)}
.matchBody{padding:8px 12px 6px}.team{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;min-height:48px}.teamLeft{display:flex;align-items:center;gap:10px;min-width:0}.teamBadge{width:35px;height:35px;border-radius:50%;background:#f5f6f7;border:1px solid #e6e8ea;display:grid;place-items:center;overflow:hidden;flex:none;font-size:9px;font-weight:1000;color:#454b51}.teamBadge img{width:100%;height:100%;object-fit:contain;background:#fff;padding:3px}.teamText{min-width:0}.teamname{font-size:13px;font-weight:950;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.abbr{font-size:8px;color:#989da3;margin-top:3px}.scoreCol{text-align:right}.score{font-size:17px;font-weight:1000;line-height:1.05;letter-spacing:.1px}.info{font-size:8px;color:#959aa0;margin-top:4px;white-space:nowrap}.divider{height:1px;background:#f3f4f5;margin:0 45px}
.matchFoot{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 12px 10px;background:#fcfcfd;border-top:1px solid #f0f1f2}.report{min-width:0;font-size:9px;color:#5d646b;line-height:1.4;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.arrow{flex:none;width:23px;height:23px;border-radius:50%;background:#f3f4f6;display:grid;place-items:center;color:#70767c;font-weight:900}
.empty,.error{background:#fff;border:1px solid var(--line);box-shadow:var(--shadow);border-radius:16px;padding:34px 18px;text-align:center;color:#767c83;font-size:11px}.emptyIcon{font-size:31px;margin-bottom:9px}.loading{padding:46px;text-align:center;color:#888e94;font-size:11px}.spin{width:27px;height:27px;border:3px solid #eceef1;border-top-color:var(--red);border-radius:50%;animation:s .7s linear infinite;margin:0 auto 10px}@keyframes s{to{transform:rotate(360deg)}}
.backBar{display:flex;align-items:center;justify-content:space-between;margin-bottom:9px}.back{border:0;background:#fff;color:#4e555c;border-radius:10px;padding:8px 10px;font-weight:900;font-size:10px;box-shadow:var(--shadow);border:1px solid var(--line)}.miniLive{font-size:8px;font-weight:1000;background:var(--redSoft);color:var(--red);padding:6px 8px;border-radius:999px;border:1px solid #ffd5da}
.scoreHero{background:#fff;border-radius:17px;box-shadow:var(--shadow2);overflow:hidden;margin-bottom:10px;border:1px solid var(--line)}.scoreTop{display:flex;align-items:center;justify-content:space-between;padding:9px 12px;background:#fafafb;border-bottom:1px solid var(--line)}.detailLeague{font-size:9px;color:#646a70;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.matchState{font-size:8px;color:var(--red);font-weight:1000}.scoreMain{display:grid;grid-template-columns:1fr 58px 1fr;align-items:center;padding:16px 10px 13px}.heroTeam{text-align:center;min-width:0}.heroLogo{width:48px;height:48px;border-radius:50%;background:#f5f6f7;border:1px solid #e5e7e9;margin:0 auto 8px;display:grid;place-items:center;overflow:hidden;font-size:11px;font-weight:1000}.heroLogo img{width:100%;height:100%;object-fit:contain;padding:5px;background:#fff}.heroName{font-size:11px;font-weight:950;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.heroScore{font-size:18px;font-weight:1000;margin-top:5px}.heroInfo{font-size:8px;color:#93989e;margin-top:3px}.vsBox{text-align:center;color:#a0a5aa;font-size:9px;font-weight:950}.vsCircle{width:32px;height:32px;border-radius:50%;background:#f4f5f6;margin:auto;display:grid;place-items:center;color:#7a8085}.resultStrip{padding:9px 12px 10px;background:linear-gradient(90deg,#fff4f5,#fff);border-top:1px solid #f4e1e3;font-size:9px;color:#5a6066;text-align:center;font-weight:800;line-height:1.4}
.detailTabs{display:flex;gap:6px;overflow:auto;padding:2px 0 8px;scrollbar-width:none}.detailTabs::-webkit-scrollbar{display:none}.detailTab{white-space:nowrap;border:1px solid var(--line);background:#fff;color:#747a80;border-radius:999px;padding:8px 11px;font-size:9px;font-weight:950;box-shadow:0 1px 5px rgba(20,25,30,.04)}.detailTab.active{background:var(--red);border-color:var(--red);color:#fff}
.panel{background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);overflow:hidden}.panelTitle{display:flex;align-items:center;justify-content:space-between;padding:11px 12px;border-bottom:1px solid var(--line)}.panelTitle b{font-size:11px}.sourceTag{display:inline-block;border-radius:999px;padding:4px 7px;font-size:7px;font-weight:1000;background:#edf4ff;color:#1557d6}.liveSummary{padding:11px 12px;background:linear-gradient(120deg,#fff8f9,#fff)}.liveStatus{font-size:11px;font-weight:1000;color:#262a2e}.liveReport{font-size:9px;color:#70767c;margin-top:5px;line-height:1.4}.subLabel{font-size:8px;color:#9a9fa5;font-weight:950;letter-spacing:.5px;text-transform:uppercase;margin:12px 12px 7px}.livegrid{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:0 11px 11px}.mini{background:#fafafb;border:1px solid #eceef0;border-radius:12px;padding:10px}.mini b{font-size:10px}.mini span{display:block;color:#7d8389;font-size:8px;margin-top:5px;line-height:1.4}.overStrip{display:flex;gap:6px;overflow:auto;padding:0 11px 12px}.ballPill{min-width:31px;height:31px;border-radius:50%;background:#f3f4f5;color:#50565c;display:grid;place-items:center;font-size:8px;font-weight:1000;border:1px solid #e4e6e8}.ballPill.wicket{background:#ffe9ec;color:var(--red);border-color:#ffc7ce}.ballPill.boundary{background:#eaf5ff;color:#1765bd;border-color:#cde6ff}
.ballRow{display:grid;grid-template-columns:48px 1fr;gap:10px;align-items:start;border-bottom:1px solid #eef0f2;padding:11px 12px}.ballRow:last-child{border-bottom:0}.ballNo{height:31px;border-radius:9px;background:var(--redSoft);color:var(--red);display:grid;place-items:center;font-size:9px;font-weight:1000}.ballText{font-size:9px;line-height:1.5;color:#4e555c;padding-top:2px}.ballText strong{color:#17191c}.notice{background:#fff;border-bottom:1px solid #eef0f2;padding:11px 12px;color:#555d65;font-size:9px;line-height:1.5}.notice:last-child{border-bottom:0}.notice b{color:#202327}
.innings{border-top:8px solid #f3f4f5}.innings:first-child{border-top:0}.innTitle{display:flex;justify-content:space-between;gap:8px;font-weight:1000;font-size:10px;padding:10px 11px;background:#fafafb;border-bottom:1px solid var(--line)}.tableWrap{overflow:auto}.table{width:100%;border-collapse:collapse;font-size:9px;min-width:420px}.table th,.table td{padding:8px 6px;border-bottom:1px solid #eff0f2;text-align:right}.table th:first-child,.table td:first-child{text-align:left}.table th{color:#858b91;background:#fbfbfc;font-size:8px;font-weight:950}.table td:first-child{font-weight:850;color:#30353a}.pillrow{display:flex;gap:6px;flex-wrap:wrap;padding:10px 11px}.pill{border:1px solid #e3e6e8;background:#fafafb;border-radius:999px;padding:5px 8px;font-size:8px;color:#606870;font-weight:800}
.bottom{position:fixed;z-index:30;left:0;right:0;bottom:0;background:#fff;border-top:1px solid #e4e6e8;box-shadow:0 -4px 16px rgba(20,25,30,.07)}.bottomInner{height:66px;max-width:760px;margin:auto;display:grid;grid-template-columns:repeat(5,1fr)}.bottomItem{border:0;background:#fff;color:#888e94;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;font-size:8px;font-weight:900}.bottomItem .ico{font-size:16px;line-height:1}.bottomItem.active{color:var(--red)}
@media(min-width:600px){.content,.detailWrap{padding:14px}.list{grid-template-columns:1fr 1fr}.match{min-height:188px}.detailWrap{max-width:620px;margin:auto}}
</style>
</head>
<body>
<div class="topShell">
  <div class="wrap brandRow">
    <div class="brandLeft"><div class="brandMark">I</div><div class="brandText"><b>IBETIN</b><span>Cricket Live Line</span></div></div>
    <div class="liveChip"><span class="pulseDot"></span> LIVE CENTER</div>
  </div>
  <div class="navCard"><div class="wrap"><div id="homeTabs" class="navTabs">
    <button class="tab active" data-mode="live">LIVE</button><button class="tab" data-mode="upcoming">UPCOMING</button><button class="tab" data-mode="results">RESULTS</button>
  </div></div></div>
</div>
<div class="wrap">
  <div id="home" class="content">
    <div class="sectionTitle"><div><b id="sectionName">Live Matches</b><div class="status" id="status">Loading cricket data…</div></div><button class="refreshBtn" onclick="loadMode(currentMode)">↻ Refresh</button></div>
    <div class="list" id="list"></div>
  </div>
  <div id="detail" class="detailWrap" style="display:none"></div>
</div>
<div class="bottom"><div class="bottomInner">
  <button class="bottomItem active" onclick="backHome();loadMode('live')"><span class="ico">⌂</span><span>HOME</span></button>
  <button class="bottomItem" onclick="backHome();loadMode('live')"><span class="ico">●</span><span>LIVE</span></button>
  <button class="bottomItem" onclick="backHome();loadMode('upcoming')"><span class="ico">◷</span><span>SCHEDULE</span></button>
  <button class="bottomItem" onclick="backHome();loadMode('results')"><span class="ico">★</span><span>RESULTS</span></button>
  <button class="bottomItem"><span class="ico">♢</span><span>ALERTS</span></button>
</div></div>
<script>
const tg=window.Telegram&&window.Telegram.WebApp;if(tg){try{tg.ready();tg.expand();tg.setHeaderColor('#d7192d');tg.setBackgroundColor('#f2f3f5')}catch(e){}}
const qs=new URLSearchParams(location.search),TOKEN=qs.get('t')||'';let currentMode='live',currentDetail=null,currentTab='live';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const n=v=>v===null||v===undefined||v===''?'—':esc(v);
function api(params){params.t=TOKEN;return fetch('/admin/liveline/api?'+new URLSearchParams(params),{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));return j})}
function loading(el){el.innerHTML='<div class="loading"><div class="spin"></div>Loading live cricket…</div>'}
function fmtTime(raw){if(!raw)return'';try{return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(raw))}catch(e){return raw}}
function initials(t){const txt=(t?.abbr||t?.name||'T').trim();return esc((txt.split(/\s+/).map(x=>x[0]).join('').slice(0,3)||'T').toUpperCase())}
function badgeHtml(t,hero=false){const cls=hero?'heroLogo':'teamBadge';const logo=t?.logo?esc(t.logo):'';return logo?`<div class="${cls}"><img src="${logo}" alt="" onerror="this.parentElement.innerHTML='${initials(t)}'"></div>`:`<div class="${cls}">${initials(t)}</div>`}
function teamLine(t,score,info){return `<div class="team"><div class="teamLeft">${badgeHtml(t)}<div class="teamText"><div class="teamname">${esc(t?.name||t?.abbr||'Team')}</div><div class="abbr">${esc(t?.abbr||'')}</div></div></div><div class="scoreCol"><div class="score">${n(score)}</div><div class="info">${esc(info||'')}</div></div></div>`}
function modeBadge(mode,m){if(mode==='live')return '<div class="badgeLive">● LIVE</div>';if(mode==='results')return `<div class="badgeState badgeResult">${esc(m.state||'RESULT')}</div>`;return `<div class="badgeState">${esc(fmtTime(m.startTime)||m.state||'UPCOMING')}</div>`}
function renderMatches(items,mode){const list=document.getElementById('list');if(!items.length){const msg=mode==='live'?'No live cricket matches right now.':mode==='upcoming'?'No upcoming matches found in the next few days.':'No recent results found.';list.innerHTML=`<div class="empty"><div class="emptyIcon">🏏</div><b>${msg}</b><div style="margin-top:7px">Pull refresh or check another tab.</div></div>`;return}list.innerHTML=items.map(m=>`<div class="match ${mode==='live'?'liveCard':''}" data-id="${esc(m.id)}"><div class="matchHead"><div class="leagueBox"><div class="league">${esc(m.league?.name||'Cricket')}</div><div class="format">${esc(m.format||m.dayType||'')}</div></div>${modeBadge(mode,m)}</div><div class="matchBody">${teamLine(m.home,m.homeScore,m.homeInfo)}<div class="divider"></div>${teamLine(m.away,m.awayScore,m.awayInfo)}</div><div class="matchFoot"><div class="report">${esc(m.report||fmtTime(m.startTime)||m.state||'Tap for match details')}</div><div class="arrow">›</div></div></div>`).join('');list.querySelectorAll('.match').forEach(x=>x.addEventListener('click',()=>openMatch(x.dataset.id)))}
function setBottom(mode){document.querySelectorAll('.bottomItem').forEach(x=>x.classList.remove('active'));const idx=mode==='live'?1:mode==='upcoming'?2:mode==='results'?3:0;document.querySelectorAll('.bottomItem')[idx]?.classList.add('active')}
async function loadMode(mode){currentMode=mode;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.getElementById('sectionName').textContent=mode==='live'?'Live Matches':mode==='upcoming'?'Upcoming Matches':'Recent Results';setBottom(mode);const list=document.getElementById('list');loading(list);document.getElementById('status').textContent='Refreshing '+mode+' cricket…';try{const j=await api({action:'matches',mode});renderMatches(j.matches||[],mode);document.getElementById('status').textContent=`${(j.matches||[]).length} match${(j.matches||[]).length===1?'':'es'} · ${new Date(j.generatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}catch(e){list.innerHTML=`<div class="error"><b>Cricket feed unavailable</b><br><br>${esc(e.message)}</div>`;document.getElementById('status').textContent='Feed error'}}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>loadMode(b.dataset.mode)));
async function openMatch(id){document.getElementById('home').style.display='none';document.getElementById('homeTabs').style.visibility='hidden';const d=document.getElementById('detail');d.style.display='block';loading(d);try{const j=await api({action:'match',id});currentDetail=j.detail;currentTab='live';renderDetail();window.scrollTo({top:0,behavior:'smooth'})}catch(e){d.innerHTML=`<div class="backBar"><button class="back" onclick="backHome()">← Match Center</button></div><div class="error"><b>Could not load match</b><br><br>${esc(e.message)}</div>`}}
function backHome(){document.getElementById('detail').style.display='none';document.getElementById('home').style.display='block';document.getElementById('homeTabs').style.visibility='visible'}
function tabs(){return [['live','LIVE'],['scorecard','SCORECARD'],['commentary','COMMENTARY'],['stats','STATS'],['info','INFO']].map(([x,label])=>`<button class="detailTab ${currentTab===x?'active':''}" data-tab="${x}">${label}</button>`).join('')}
function heroTeam(t,score,info){return `<div class="heroTeam">${badgeHtml(t,true)}<div class="heroName">${esc(t?.abbr||t?.name||'Team')}</div><div class="heroScore">${n(score)}</div><div class="heroInfo">${esc(info||'')}</div></div>`}
function renderDetail(){const d=document.getElementById('detail'),m=currentDetail.match||{};d.innerHTML=`<div class="backBar"><button class="back" onclick="backHome()">← Match Center</button><div class="miniLive">${esc(m.state||'MATCH')}</div></div><div class="scoreHero"><div class="scoreTop"><div class="detailLeague">${esc(m.league?.name||'Cricket')} ${m.format?'· '+esc(m.format):''}</div><div class="matchState">${esc(m.state||'')}</div></div><div class="scoreMain">${heroTeam(m.home,m.homeScore,m.homeInfo)}<div class="vsBox"><div class="vsCircle">VS</div></div>${heroTeam(m.away,m.awayScore,m.awayInfo)}</div><div class="resultStrip">${esc(m.report||fmtTime(m.startTime)||'Live match updates')}</div></div><div class="detailTabs">${tabs()}</div><div id="panel" class="panel"></div>`;d.querySelectorAll('.detailTab').forEach(b=>b.addEventListener('click',()=>{currentTab=b.dataset.tab;renderDetail()}));renderPanel()}
function playerName(o){return o?.player?.name||o?.name||'Player'}
function recentBalls(tl){if(!tl?.length)return '';return `<div class="subLabel">Recent balls</div><div class="overStrip">${tl.slice(-6).map(e=>{const txt=String(e.runs??e.run??e.event??'•');const wicket=!!e.wicket||/wicket|out/i.test(String(e.commentary||''));const boundary=/\b4\b|four|\b6\b|six/i.test(String(e.commentary||''))||txt==='4'||txt==='6';return `<div class="ballPill ${wicket?'wicket':boundary?'boundary':''}">${wicket?'W':esc(txt).slice(0,3)}</div>`}).join('')}</div>`}
function renderPanel(){const p=document.getElementById('panel'),x=currentDetail||{},m=x.match||{};if(currentTab==='live'){const bats=x.inplayData?.batsmen||[],bowls=x.inplayData?.bowlers||[];const cards=[...bats.slice(0,2).map(v=>`<div class="mini"><b>🏏 ${esc(playerName(v))}</b><span>${n(v.player?.statistics?.runs)} runs · ${n(v.player?.statistics?.balls)} balls · SR ${n(v.player?.statistics?.strikeRate)}</span></div>`),...bowls.slice(0,1).map(v=>`<div class="mini"><b>🎯 ${esc(playerName(v))}</b><span>${n(v.player?.statistics?.overs)} ov · ${n(v.player?.statistics?.wickets)} wkts · Econ ${n(v.player?.statistics?.economy)}</span></div>`)].join('');p.innerHTML=`<div class="panelTitle"><b>LIVE MATCH</b><span class="sourceTag">LIVE LINE</span></div><div class="liveSummary"><div class="liveStatus">${esc(m.state||'Match in progress')}</div><div class="liveReport">${esc(m.report||'Live score updates from the connected cricket feed.')}</div></div><div class="subLabel">At the crease</div><div class="livegrid">${cards||'<div class="mini"><b>Live player data</b><span>Waiting for in-play player data.</span></div>'}</div>${recentBalls(x.timeline||[])}`}else if(currentTab==='scorecard'){p.innerHTML='<div class="panelTitle"><b>FULL SCORECARD</b></div>'+scorecardHtml(x.statistics||[])}else if(currentTab==='commentary'){const tl=x.timeline||[],source=x.timelineSource?`<span class="sourceTag">${esc(x.timelineSource)}</span>`:'';p.innerHTML=`<div class="panelTitle"><b>BALL-BY-BALL</b>${source}</div>`+(tl.length?tl.slice().reverse().map((e,i)=>`<div class="ballRow"><div class="ballNo">${esc(e.over||e.ball||e.time||('#'+(i+1)))}</div><div class="ballText"><strong>${e.wicket?'WICKET · ':''}</strong>${esc(e.commentary||e.description||e.text||e.event||JSON.stringify(e).slice(0,220))}</div></div>`).join(''):'<div class="notice">Ball-by-ball commentary is not available for this match yet.</div>')}else if(currentTab==='stats'){p.innerHTML='<div class="panelTitle"><b>MATCH STATS</b></div>'+statsHtml(x.statistics||[])}else{const v=x.venue||{},f=x.forecast||{};p.innerHTML=`<div class="panelTitle"><b>MATCH INFO</b></div><div class="pillrow"><span class="pill">${esc(m.format||'Cricket')}</span><span class="pill">${esc(m.state||'')}</span><span class="pill">${esc(m.league?.name||'')}</span></div><div class="notice"><b>Venue</b><br>${esc(v.name||'—')}${v.city?' · '+esc(v.city):''}${v.country?' · '+esc(v.country):''}</div><div class="notice"><b>Weather</b><br>${esc(f.status||'—')}${f.temperature?' · '+esc(f.temperature):''}</div>`}}
function scorecardHtml(stats){if(!stats.length)return '<div class="notice">Scorecard data is not available for this match yet.</div>';return stats.map((inn,i)=>{const bats=inn.inningBatsmen||[],bowl=inn.inningBowlers||[];return `<div class="innings"><div class="innTitle"><span>${esc(inn.name||inn.abbreviation||('Innings '+(inn.inningNumber||i+1)))}</span><span>${n(inn.inningNumber?'#'+inn.inningNumber:'')}</span></div><div class="tableWrap"><table class="table"><thead><tr><th>BATTER</th><th>R</th><th>B</th><th>4</th><th>6</th><th>SR</th></tr></thead><tbody>${bats.map(b=>`<tr><td>${esc(playerName(b))}</td><td>${n(b.runs)}</td><td>${n(b.balls)}</td><td>${n(b.fours)}</td><td>${n(b.sixes)}</td><td>${n(b.battingStrikeRate)}</td></tr>`).join('')}</tbody></table></div><div class="tableWrap"><table class="table"><thead><tr><th>BOWLER</th><th>O</th><th>R</th><th>W</th><th>ECON</th></tr></thead><tbody>${bowl.map(b=>`<tr><td>${esc(playerName(b))}</td><td>${n(b.overs)}</td><td>${n(b.concededRuns??b.runsConceded)}</td><td>${n(b.wickets)}</td><td>${n(b.economy)}</td></tr>`).join('')}</tbody></table></div></div>`}).join('')}
function statsHtml(stats){if(!stats.length)return '<div class="notice">Detailed innings statistics are not available for this match yet.</div>';return stats.map((inn,i)=>`<div class="innings"><div class="innTitle"><span>${esc(inn.name||inn.abbreviation||('Innings '+(inn.inningNumber||i+1)))}</span></div><div class="pillrow"><span class="pill">4s: ${n(inn.fours)}</span><span class="pill">6s: ${n(inn.sixes)}</span><span class="pill">Extras: ${n(inn.extras)}</span><span class="pill">Wides: ${n(inn.wides)}</span><span class="pill">No-balls: ${n(inn.noBalls)}</span></div>${(inn.inningPartnerships||[]).slice(-3).reverse().map(q=>`<div class="notice"><b>Partnership</b> · ${n(q.runs)} runs / ${n(q.balls)} balls<br>${esc(q.firstPlayer?.name||'')} + ${esc(q.secondPlayer?.name||'')}</div>`).join('')}</div>`).join('')}
loadMode('live');
</script>
</body>
</html>'''


liveline.admin_url = _light_admin_url
liveline._page = _light_page

import ibetin_admin_fix_start as app

if __name__ == "__main__":
    app.base.ibetin_start.main()
