import os
from urllib.parse import urlencode

import ibetin_liveline_trial as liveline


def _light_admin_url() -> str:
    root = os.getenv("TRACKING_BASE_URL", "").strip().rstrip("/") or "https://ibetin-app-production.up.railway.app"
    return f"{root}{liveline.LIVELINE_PATH}?{urlencode({'t': liveline._token(), 'v': '20260916-v2-light'})}"


def _light_page() -> str:
    return r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate">
<meta name="referrer" content="no-referrer">
<title>IBETIN Live Line</title>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>
:root{--bg:#f4f5f7;--card:#fff;--text:#17191c;--muted:#7d838a;--line:#e7e9ec;--red:#e51d31;--soft:#fafbfc;--shadow:0 2px 12px rgba(25,31,38,.07)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:Arial,Helvetica,sans-serif}body{padding:0 0 70px}button{font:inherit}.wrap{max-width:760px;margin:auto}
.appbar{position:sticky;top:0;z-index:10;background:#fff;border-bottom:1px solid var(--line);box-shadow:0 1px 6px rgba(0,0,0,.04)}.brandrow{height:56px;display:flex;align-items:center;justify-content:space-between;padding:0 14px}.logo{display:flex;align-items:center;gap:9px;font-weight:950;font-size:18px}.mark{width:31px;height:31px;border-radius:9px;background:linear-gradient(145deg,#e51d31,#ff5260);display:grid;place-items:center;color:#fff;font-weight:950}.beta{font-size:9px;font-weight:900;color:var(--red);background:#fff5f6;border:1px solid #f2c0c6;border-radius:999px;padding:5px 8px}
.navtabs{display:grid;grid-template-columns:repeat(3,1fr);padding:0 8px}.tab{position:relative;border:0;background:#fff;color:#757b82;padding:12px 3px 13px;font-size:12px;font-weight:900}.tab.active{color:var(--red)}.tab.active:after{content:"";position:absolute;left:20%;right:20%;bottom:0;height:3px;background:var(--red);border-radius:3px 3px 0 0}
.content,.detailWrap{padding:11px}.status{font-size:10px;color:#92979d;margin:2px 2px 8px}.list{display:grid;gap:10px}.match{background:#fff;border:1px solid var(--line);border-radius:13px;box-shadow:var(--shadow);overflow:hidden;cursor:pointer}.matchHead{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 11px 8px;border-bottom:1px solid #f0f1f2}.league{min-width:0;font-size:10px;font-weight:850;color:#60666d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.live{font-size:9px;font-weight:950;color:#fff;background:var(--red);border-radius:5px;padding:4px 7px}.state{font-size:9px;font-weight:900;color:#596068;background:#f0f2f4;border-radius:5px;padding:4px 7px}.matchBody{padding:9px 11px}.team{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;min-height:41px}.teamLeft{display:flex;align-items:center;gap:9px;min-width:0}.teamDot{width:29px;height:29px;border-radius:50%;background:#f1f3f5;border:1px solid #e1e4e7;display:grid;place-items:center;font-size:9px;font-weight:950;color:#4b535c;flex:none}.teamname{font-size:13px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.score{font-size:16px;font-weight:950;text-align:right}.info{font-size:9px;color:#93989e;margin-top:2px}.matchFoot{padding:8px 11px 9px;background:#fcfcfd;border-top:1px solid #f0f1f2;font-size:10px;color:#5d646b;line-height:1.35}
.empty,.error{background:#fff;border:1px solid var(--line);box-shadow:var(--shadow);border-radius:13px;padding:30px 18px;text-align:center;color:#777d84;font-size:12px}.emptyIcon{font-size:28px;margin-bottom:8px}.loading{padding:40px;text-align:center;color:#8b9197;font-size:12px}.spin{width:25px;height:25px;border:3px solid #eceef1;border-top-color:var(--red);border-radius:50%;animation:s .7s linear infinite;margin:0 auto 10px}@keyframes s{to{transform:rotate(360deg)}}
.back{border:1px solid var(--line);background:#fff;color:#4e565e;border-radius:9px;padding:8px 10px;font-weight:850;font-size:11px;margin-bottom:9px}.detailHead{background:#fff;border:1px solid var(--line);border-radius:14px;box-shadow:var(--shadow);overflow:hidden;margin-bottom:10px}.detailLeague{padding:9px 11px;background:#fafafa;border-bottom:1px solid var(--line);font-size:10px;color:#666c73;font-weight:850}.scoreHero{padding:13px}.bigScore{font-size:19px;font-weight:950;line-height:1.55}.sub{font-size:10px;color:#777d84;margin-top:5px;line-height:1.4}.detailTabs{display:flex;gap:0;overflow:auto;background:#fff;border:1px solid var(--line);border-radius:12px;margin-bottom:10px;box-shadow:var(--shadow)}.detailTab{position:relative;white-space:nowrap;border:0;background:#fff;color:#747a81;padding:11px 13px;font-size:10px;font-weight:900}.detailTab.active{color:var(--red)}.detailTab.active:after{content:"";position:absolute;left:16%;right:16%;bottom:0;height:3px;background:var(--red);border-radius:3px 3px 0 0}
.panel{background:#fff;border:1px solid var(--line);border-radius:13px;box-shadow:var(--shadow);overflow:hidden}.panel h3{margin:0;padding:11px 12px;border-bottom:1px solid var(--line);font-size:12px}.livegrid{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:11px}.mini{background:#fafafa;border:1px solid #eceef0;border-radius:10px;padding:10px}.mini b{font-size:11px}.mini span{display:block;color:#7c838a;font-size:9px;margin-top:4px;line-height:1.35}.notice{background:#fff;border-bottom:1px solid #eef0f2;padding:11px 12px;color:#555d65;font-size:10px;line-height:1.5}.notice:last-child{border-bottom:0}.notice b{color:#202327}.ballRow{display:grid;grid-template-columns:48px 1fr;gap:9px;align-items:start;border-bottom:1px solid #eef0f2;padding:10px 12px}.ballRow:last-child{border-bottom:0}.ballNo{height:30px;border-radius:7px;background:#fff1f2;color:var(--red);display:grid;place-items:center;font-size:10px;font-weight:950}.ballText{font-size:10px;line-height:1.45;color:#4e555c;padding-top:2px}.ballText strong{color:#17191c}.sourceTag{display:inline-block;margin-left:5px;border-radius:999px;padding:3px 6px;font-size:8px;font-weight:900;background:#eef5ff;color:#1557d6}
.innings{border-top:8px solid #f4f5f7}.innings:first-child{border-top:0}.innTitle{display:flex;justify-content:space-between;gap:8px;font-weight:950;font-size:11px;padding:10px 11px;background:#fbfbfc;border-bottom:1px solid var(--line)}.tableWrap{overflow:auto}.table{width:100%;border-collapse:collapse;font-size:9px;min-width:420px}.table th,.table td{padding:8px 6px;border-bottom:1px solid #eff0f2;text-align:right}.table th:first-child,.table td:first-child{text-align:left}.table th{color:#82888f;background:#fafafa;font-size:8px}.pillrow{display:flex;gap:6px;flex-wrap:wrap;padding:10px 11px}.pill{border:1px solid #e4e6e9;background:#fafafa;border-radius:999px;padding:5px 8px;font-size:9px;color:#606870}
.bottom{position:fixed;z-index:12;left:0;right:0;bottom:0;background:#fff;border-top:1px solid #e5e7ea;box-shadow:0 -2px 10px rgba(20,25,30,.05)}.bottomInner{height:62px;max-width:760px;margin:auto;display:grid;grid-template-columns:repeat(4,1fr)}.bottomItem{border:0;background:#fff;color:#838990;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;font-size:9px;font-weight:800}.bottomItem span:first-child{font-size:17px}.bottomItem.active{color:var(--red)}
</style>
</head>
<body>
<div class="appbar"><div class="wrap"><div class="brandrow"><div class="logo"><span class="mark">I</span><span>IBETIN Live Line</span></div><div class="beta">BETA</div></div><div id="homeTabs" class="navtabs"><button class="tab active" data-mode="live">LIVE</button><button class="tab" data-mode="upcoming">UPCOMING</button><button class="tab" data-mode="results">RESULTS</button></div></div></div>
<div class="wrap"><div id="home" class="content"><div class="status" id="status">Loading cricket data…</div><div class="list" id="list"></div></div><div id="detail" class="detailWrap" style="display:none"></div></div>
<div class="bottom"><div class="bottomInner"><button class="bottomItem active" onclick="backHome()"><span>🏠</span><span>Home</span></button><button class="bottomItem" onclick="loadMode('live');backHome()"><span>🔴</span><span>Live</span></button><button class="bottomItem" onclick="loadMode('results');backHome()"><span>🏆</span><span>Results</span></button><button class="bottomItem"><span>🔔</span><span>Alerts</span></button></div></div>
<script>
const tg=window.Telegram&&window.Telegram.WebApp;if(tg){try{tg.ready();tg.expand();tg.setHeaderColor('#ffffff');tg.setBackgroundColor('#f4f5f7')}catch(e){}}
const qs=new URLSearchParams(location.search),TOKEN=qs.get('t')||'';let currentMode='live',currentDetail=null,currentTab='live';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const n=v=>v===null||v===undefined||v===''?'—':esc(v);
function api(params){params.t=TOKEN;return fetch('/admin/liveline/api?'+new URLSearchParams(params),{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));return j})}
function loading(el){el.innerHTML='<div class="loading"><div class="spin"></div>Loading…</div>'}
function fmtTime(raw){if(!raw)return'';try{return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(raw))}catch(e){return raw}}
function initials(t){const txt=(t?.abbr||t?.name||'T').trim();return esc((txt.split(/\s+/).map(x=>x[0]).join('').slice(0,3)||'T').toUpperCase())}
function teamLine(t,score,info){return `<div class="team"><div class="teamLeft"><div class="teamDot">${initials(t)}</div><div><div class="teamname">${esc(t?.name||t?.abbr||'Team')}</div><div class="info">${esc(t?.abbr||'')}</div></div></div><div><div class="score">${n(score)}</div><div class="info">${esc(info||'')}</div></div></div>`}
function renderMatches(items,mode){const list=document.getElementById('list');if(!items.length){const msg=mode==='live'?'No live cricket matches right now.':mode==='upcoming'?'No upcoming matches found in the next few days.':'No recent results found.';list.innerHTML=`<div class="empty"><div class="emptyIcon">🏏</div><b>${msg}</b><div style="margin-top:7px">Check another tab for more matches.</div></div>`;return}list.innerHTML=items.map(m=>`<div class="match" data-id="${esc(m.id)}"><div class="matchHead"><div class="league">${esc(m.league?.name||m.format||'Cricket')}</div>${mode==='live'?'<div class="live">● LIVE</div>':`<div class="state">${esc(m.state||fmtTime(m.startTime)||'')}</div>`}</div><div class="matchBody">${teamLine(m.home,m.homeScore,m.homeInfo)}${teamLine(m.away,m.awayScore,m.awayInfo)}</div><div class="matchFoot">${esc(m.report||fmtTime(m.startTime)||m.state||'Tap to view match')}</div></div>`).join('');list.querySelectorAll('.match').forEach(x=>x.addEventListener('click',()=>openMatch(x.dataset.id)))}
async function loadMode(mode){currentMode=mode;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));const list=document.getElementById('list');loading(list);document.getElementById('status').textContent='Refreshing '+mode+' cricket…';try{const j=await api({action:'matches',mode});renderMatches(j.matches||[],mode);document.getElementById('status').textContent=`${(j.matches||[]).length} match${(j.matches||[]).length===1?'':'es'} · updated ${new Date(j.generatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}catch(e){list.innerHTML=`<div class="error"><b>Cricket feed unavailable</b><br><br>${esc(e.message)}</div>`;document.getElementById('status').textContent='Feed error'}}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>loadMode(b.dataset.mode)));
async function openMatch(id){document.getElementById('home').style.display='none';document.getElementById('homeTabs').style.visibility='hidden';const d=document.getElementById('detail');d.style.display='block';loading(d);try{const j=await api({action:'match',id});currentDetail=j.detail;currentTab='live';renderDetail()}catch(e){d.innerHTML=`<button class="back" onclick="backHome()">← Match Center</button><div class="error"><b>Could not load match</b><br><br>${esc(e.message)}</div>`}}
function backHome(){document.getElementById('detail').style.display='none';document.getElementById('home').style.display='block';document.getElementById('homeTabs').style.visibility='visible'}
function tabs(){return ['live','scorecard','commentary','stats','info'].map(x=>`<button class="detailTab ${currentTab===x?'active':''}" data-tab="${x}">${x.toUpperCase()}</button>`).join('')}
function renderDetail(){const d=document.getElementById('detail'),m=currentDetail.match||{};d.innerHTML=`<button class="back" onclick="backHome()">← Match Center</button><div class="detailHead"><div class="detailLeague">${esc(m.league?.name||'Cricket')} ${m.format?'· '+esc(m.format):''}</div><div class="scoreHero"><div class="bigScore">${esc(m.home?.name||'Home')} &nbsp; ${n(m.homeScore)}<br>${esc(m.away?.name||'Away')} &nbsp; ${n(m.awayScore)}</div><div class="sub">${esc(m.report||m.state||'')} ${m.startTime?'· '+esc(fmtTime(m.startTime)):''}</div></div></div><div class="detailTabs">${tabs()}</div><div id="panel" class="panel"></div>`;d.querySelectorAll('.detailTab').forEach(b=>b.addEventListener('click',()=>{currentTab=b.dataset.tab;renderDetail()}));renderPanel()}
function playerName(o){return o?.player?.name||o?.name||'Player'}
function renderPanel(){const p=document.getElementById('panel'),x=currentDetail||{},m=x.match||{};if(currentTab==='live'){const bats=x.inplayData?.batsmen||[],bowls=x.inplayData?.bowlers||[];const cards=[...bats.slice(0,2).map(v=>`<div class="mini"><b>🏏 ${esc(playerName(v))}</b><span>${n(v.player?.statistics?.runs)} runs · ${n(v.player?.statistics?.balls)} balls · SR ${n(v.player?.statistics?.strikeRate)}</span></div>`),...bowls.slice(0,1).map(v=>`<div class="mini"><b>🎯 ${esc(playerName(v))}</b><span>${n(v.player?.statistics?.overs)} ov · ${n(v.player?.statistics?.wickets)} wkts · Econ ${n(v.player?.statistics?.economy)}</span></div>`)].join('');p.innerHTML=`<h3>LIVE LINE</h3><div class="livegrid">${cards||'<div class="mini"><b>Live player data</b><span>Waiting for in-play player data.</span></div>'}</div><div class="notice"><b>${esc(m.state||'Match status')}</b><br>${esc(m.report||'Live score updates are coming from the connected cricket feed.')}</div>`}else if(currentTab==='scorecard'){p.innerHTML='<h3>SCORECARD</h3>'+scorecardHtml(x.statistics||[])}else if(currentTab==='commentary'){const tl=x.timeline||[],source=x.timelineSource?`<span class="sourceTag">${esc(x.timelineSource)}</span>`:'';p.innerHTML=`<h3>BALL-BY-BALL ${source}</h3>`+(tl.length?tl.slice().reverse().map((e,i)=>`<div class="ballRow"><div class="ballNo">${esc(e.over||e.ball||e.time||('#'+(i+1)))}</div><div class="ballText"><strong>${e.wicket?'WICKET · ':''}</strong>${esc(e.commentary||e.description||e.text||e.event||JSON.stringify(e).slice(0,220))}</div></div>`).join(''):'<div class="notice">Ball-by-ball commentary is not available for this match yet.</div>')}else if(currentTab==='stats'){p.innerHTML='<h3>MATCH STATS</h3>'+statsHtml(x.statistics||[])}else{const v=x.venue||{},f=x.forecast||{};p.innerHTML=`<h3>MATCH INFO</h3><div class="pillrow"><span class="pill">${esc(m.format||'Cricket')}</span><span class="pill">${esc(m.state||'')}</span><span class="pill">${esc(m.league?.name||'')}</span></div><div class="notice"><b>Venue</b><br>${esc(v.name||'—')}${v.city?' · '+esc(v.city):''}${v.country?' · '+esc(v.country):''}</div><div class="notice"><b>Weather</b><br>${esc(f.status||'—')}${f.temperature?' · '+esc(f.temperature):''}</div>`}}
function scorecardHtml(stats){if(!stats.length)return '<div class="notice">Scorecard data is not available for this match yet.</div>';return stats.map((inn,i)=>{const bats=inn.inningBatsmen||[],bowl=inn.inningBowlers||[];return `<div class="innings"><div class="innTitle"><span>${esc(inn.name||inn.abbreviation||('Innings '+(inn.inningNumber||i+1)))}</span><span>${n(inn.inningNumber?'#'+inn.inningNumber:'')}</span></div><div class="tableWrap"><table class="table"><thead><tr><th>BATTER</th><th>R</th><th>B</th><th>4</th><th>6</th><th>SR</th></tr></thead><tbody>${bats.map(b=>`<tr><td>${esc(playerName(b))}</td><td>${n(b.runs)}</td><td>${n(b.balls)}</td><td>${n(b.fours)}</td><td>${n(b.sixes)}</td><td>${n(b.battingStrikeRate)}</td></tr>`).join('')}</tbody></table></div><div class="tableWrap"><table class="table"><thead><tr><th>BOWLER</th><th>O</th><th>R</th><th>W</th><th>ECON</th></tr></thead><tbody>${bowl.map(b=>`<tr><td>${esc(playerName(b))}</td><td>${n(b.overs)}</td><td>${n(b.concededRuns??b.runsConceded)}</td><td>${n(b.wickets)}</td><td>${n(b.economy)}</td></tr>`).join('')}</tbody></table></div></div>`}).join('')}
function statsHtml(stats){if(!stats.length)return '<div class="notice">Detailed innings statistics are not available for this match yet.</div>';return stats.map((inn,i)=>`<div class="innings"><div class="innTitle"><span>${esc(inn.name||inn.abbreviation||('Innings '+(inn.inningNumber||i+1)))}</span></div><div class="pillrow"><span class="pill">4s: ${n(inn.fours)}</span><span class="pill">6s: ${n(inn.sixes)}</span><span class="pill">Extras: ${n(inn.extras)}</span><span class="pill">Wides: ${n(inn.wides)}</span><span class="pill">No-balls: ${n(inn.noBalls)}</span></div>${(inn.inningPartnerships||[]).slice(-3).reverse().map(q=>`<div class="notice"><b>Partnership</b> · ${n(q.runs)} runs / ${n(q.balls)} balls<br>${esc(q.firstPlayer?.name||'')} + ${esc(q.secondPlayer?.name||'')}</div>`).join('')}</div>`).join('')}
loadMode('live');
</script>
</body>
</html>'''


liveline.admin_url = _light_admin_url
liveline._page = _light_page

import ibetin_admin_fix_start as app

if __name__ == "__main__":
    app.base.ibetin_start.main()
