import os
from urllib.parse import urlencode

import ibetin_liveline_trial as liveline


def _exact_admin_url() -> str:
    root = os.getenv("TRACKING_BASE_URL", "").strip().rstrip("/") or "https://ibetin-app-production.up.railway.app"
    return f"{root}{liveline.LIVELINE_PATH}?{urlencode({'t': liveline._token(), 'v': '20260916-v6-exact-ibetin'})}"


def _exact_page() -> str:
    return r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate">
<meta name="referrer" content="no-referrer">
<title>IBETIN Live Line</title>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
:root{--bg:#f5f7fb;--ink:#172033;--muted:#64748b;--muted2:#738196;--line:#dce3ed;--soft:#f8fafc;--blue:#2563eb;--red:#e11d48;--green:#15803d}
html,body{margin:0;min-height:100%;background:var(--bg);color:var(--ink);font-family:Inter,Arial,Helvetica,sans-serif}
body{padding-bottom:82px}.wrap{max-width:760px;margin:0 auto;padding:16px 14px 28px}button{font:inherit}
.top{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.brand{font-size:20px;font-weight:950;letter-spacing:.7px}.pill{border:1px solid var(--line);background:#fff;border-radius:999px;padding:6px 9px;color:#65758a;font-size:10px;font-weight:900}
.hero{background:#fff;border:1px solid var(--line);border-radius:22px;padding:20px 18px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:1.1px;color:var(--muted);margin-bottom:8px}.hero h1{font-size:27px;line-height:1.08;margin:0 0 8px}.hero p{margin:0;color:var(--muted);font-size:13px;line-height:1.5}
.modeTabs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.modeTab{border:1px solid var(--line);background:#fff;color:#475569;border-radius:14px;padding:12px 8px;font-size:11px;font-weight:900}.modeTab.active{background:var(--ink);color:#fff;border-color:var(--ink)}
.section{margin-top:14px}.sectionHead{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}.sectionHead b{font-size:13px}.status{color:var(--muted2);font-size:10px}.refresh{border:1px solid var(--line);background:#fff;color:#475569;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:900}
.list{display:grid;gap:10px}.match{background:#fff;border:1px solid var(--line);border-radius:18px;overflow:hidden}.matchTop{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 13px;border-bottom:1px solid #edf1f6}.league{min-width:0;font-size:11px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.format{font-size:9px;color:var(--muted2);margin-top:3px}.liveTag,.stateTag{flex:none;border-radius:999px;padding:5px 8px;font-size:8px;font-weight:950}.liveTag{background:#fff1f2;color:var(--red);border:1px solid #ffe4e6}.stateTag{background:#f1f5f9;color:#475569}.resultTag{background:#ecfdf5;color:var(--green)}
.matchBody{padding:9px 13px}.team{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;min-height:48px}.teamLeft{display:flex;align-items:center;gap:10px;min-width:0}.teamBadge{width:36px;height:36px;border-radius:12px;background:var(--soft);border:1px solid var(--line);display:grid;place-items:center;overflow:hidden;flex:none;font-size:9px;font-weight:950;color:#475569}.teamBadge img{width:100%;height:100%;object-fit:contain;padding:4px;background:#fff}.teamText{min-width:0}.teamName{font-size:13px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.abbr{font-size:9px;color:var(--muted2);margin-top:3px}.score{text-align:right;font-size:17px;font-weight:950}.scoreInfo{text-align:right;font-size:9px;color:var(--muted2);margin-top:3px}.matchFoot{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:10px 13px;background:#fbfcfe;border-top:1px solid #edf1f6}.report{min-width:0;font-size:10px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.go{font-size:16px;color:#94a3b8}
.empty,.error{background:#fff;border:1px solid var(--line);border-radius:18px;padding:30px 18px;text-align:center;color:var(--muted);font-size:12px}.loading{padding:40px;text-align:center;color:var(--muted2);font-size:12px}.spin{width:28px;height:28px;margin:0 auto 10px;border:3px solid #e2e8f0;border-top-color:var(--blue);border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.detailWrap{display:none}.backRow{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.back{border:1px solid var(--line);background:#fff;color:var(--ink);border-radius:12px;padding:9px 11px;font-size:10px;font-weight:900}.detailLive{border:1px solid #ffe4e6;background:#fff1f2;color:var(--red);border-radius:999px;padding:6px 9px;font-size:9px;font-weight:900}
.scoreCard{background:#fff;border:1px solid var(--line);border-radius:22px;overflow:hidden}.scoreMeta{padding:11px 13px;background:var(--soft);border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:10px}.scoreLeague{font-size:10px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.scoreState{font-size:9px;color:var(--muted)}.versus{display:grid;grid-template-columns:1fr 44px 1fr;gap:8px;align-items:center;padding:18px 10px}.side{text-align:center;min-width:0}.sideLogo{width:50px;height:50px;border-radius:14px;background:var(--soft);border:1px solid var(--line);display:grid;place-items:center;overflow:hidden;margin:0 auto 8px;font-size:10px;font-weight:950;color:#475569}.sideLogo img{width:100%;height:100%;object-fit:contain;padding:5px;background:#fff}.sideName{font-size:11px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sideScore{font-size:20px;font-weight:950;margin-top:6px}.sideInfo{font-size:8px;color:var(--muted2);margin-top:3px}.vs{width:34px;height:34px;border-radius:50%;background:#eef2f7;color:#64748b;display:grid;place-items:center;font-size:9px;font-weight:950;margin:auto}.result{padding:10px 13px;background:#fbfcfe;border-top:1px solid var(--line);text-align:center;color:#475569;font-size:10px;line-height:1.45}
.detailTabs{display:flex;gap:8px;overflow:auto;margin:12px 0 10px;scrollbar-width:none}.detailTabs::-webkit-scrollbar{display:none}.detailTab{white-space:nowrap;border:1px solid var(--line);background:#fff;color:#475569;border-radius:999px;padding:9px 12px;font-size:9px;font-weight:900}.detailTab.active{background:var(--ink);color:#fff;border-color:var(--ink)}
.panel{background:#fff;border:1px solid var(--line);border-radius:18px;overflow:hidden}.panelTitle{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:12px 13px;border-bottom:1px solid var(--line)}.panelTitle b{font-size:12px}.sourceTag{background:#eff6ff;color:var(--blue);border-radius:999px;padding:4px 7px;font-size:8px;font-weight:900}.notice{padding:12px 13px;border-bottom:1px solid #edf1f6;color:#475569;font-size:10px;line-height:1.5}.notice:last-child{border-bottom:0}.notice b{color:var(--ink)}
.liveGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px;padding:12px}.mini{background:var(--soft);border:1px solid #e2e8f0;border-radius:14px;padding:11px}.mini b{font-size:10px}.mini span{display:block;color:var(--muted);font-size:8px;line-height:1.45;margin-top:5px}.ballRow{display:grid;grid-template-columns:46px 1fr;gap:10px;padding:11px 13px;border-bottom:1px solid #edf1f6}.ballNo{height:31px;border-radius:10px;background:#eff6ff;color:var(--blue);display:grid;place-items:center;font-size:9px;font-weight:950}.ballText{font-size:10px;line-height:1.5;color:#475569}.ballText strong{color:var(--ink)}
.innings{border-top:8px solid var(--bg)}.innings:first-child{border-top:0}.innTitle{display:flex;justify-content:space-between;gap:8px;padding:10px 11px;background:var(--soft);border-bottom:1px solid var(--line);font-size:10px;font-weight:950}.tableWrap{overflow:auto}.table{width:100%;min-width:420px;border-collapse:collapse;font-size:9px}.table th,.table td{padding:8px 6px;border-bottom:1px solid #edf1f6;text-align:right}.table th:first-child,.table td:first-child{text-align:left}.table th{background:#fbfcfe;color:var(--muted);font-size:8px}.table td:first-child{font-weight:850}.pillrow{display:flex;gap:6px;flex-wrap:wrap;padding:11px}.statPill{border:1px solid var(--line);background:var(--soft);border-radius:999px;padding:6px 8px;color:#475569;font-size:8px;font-weight:800}
.nav{position:fixed;left:0;right:0;bottom:0;background:rgba(255,255,255,.97);border-top:1px solid var(--line);padding:9px 12px max(9px,env(safe-area-inset-bottom));display:flex;justify-content:center;gap:6px;z-index:20}.nav button{flex:1;max-width:160px;border:0;background:transparent;text-align:center;color:var(--muted);font-size:10px;font-weight:900;padding:7px 4px;border-radius:11px}.nav button strong{display:block;color:var(--ink);font-size:17px;margin-bottom:2px}.nav button.active{background:#f1f5f9;color:var(--ink)}
@media(min-width:600px){.list{grid-template-columns:1fr 1fr}.detailWrap{max-width:620px;margin:auto}}
</style>
</head>
<body>
<div class="wrap">
  <div class="top"><div class="brand">IBETIN</div><div class="pill">LIVE LINE</div></div>
  <div id="home">
    <section class="hero"><div class="eyebrow">IBETIN CRICKET</div><h1>Live Match Center</h1><p>Live scores, commentary, scorecards, upcoming matches and results — inside the same IBETIN experience.</p></section>
    <div class="modeTabs"><button class="modeTab active" data-mode="live">LIVE</button><button class="modeTab" data-mode="upcoming">UPCOMING</button><button class="modeTab" data-mode="results">RESULTS</button></div>
    <section class="section"><div class="sectionHead"><div><b id="sectionTitle">Live Matches</b><div id="status" class="status">Loading cricket data…</div></div><button class="refresh" onclick="loadMode(currentMode)">Refresh</button></div><div id="list" class="list"></div></section>
  </div>
  <div id="detail" class="detailWrap"></div>
</div>
<nav class="nav"><button class="active" onclick="backHome()"><strong>⌂</strong>Home</button><button onclick="loadMode('live');backHome()"><strong>●</strong>Live</button><button onclick="loadMode('results');backHome()"><strong>▣</strong>Results</button><button><strong>🔔</strong>Alerts</button></nav>
<script>
const tg=window.Telegram&&window.Telegram.WebApp;if(tg){try{tg.ready();tg.expand();tg.setHeaderColor('#ffffff');tg.setBackgroundColor('#f5f7fb')}catch(e){}}
const qs=new URLSearchParams(location.search),TOKEN=qs.get('t')||'';let currentMode='live',currentDetail=null,currentTab='live';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const n=v=>v===null||v===undefined||v===''?'—':esc(v);
function api(params){params.t=TOKEN;return fetch('/admin/liveline/api?'+new URLSearchParams(params),{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));return j})}
function loading(el){el.innerHTML='<div class="loading"><div class="spin"></div>Loading…</div>'}
function fmtTime(raw){if(!raw)return'';try{return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(raw))}catch(e){return raw}}
function initials(t){const txt=(t?.abbr||t?.name||'T').trim();return esc((txt.split(/\s+/).map(x=>x[0]).join('').slice(0,3)||'T').toUpperCase())}
function logo(t,cls='teamBadge'){return t?.logo?`<div class="${cls}"><img src="${esc(t.logo)}" alt=""></div>`:`<div class="${cls}">${initials(t)}</div>`}
function teamLine(t,score,info){return `<div class="team"><div class="teamLeft">${logo(t)}<div class="teamText"><div class="teamName">${esc(t?.name||t?.abbr||'Team')}</div><div class="abbr">${esc(t?.abbr||'')}</div></div></div><div><div class="score">${n(score)}</div><div class="scoreInfo">${esc(info||'')}</div></div></div>`}
function renderMatches(items,mode){const list=document.getElementById('list');if(!items.length){const msg=mode==='live'?'No live cricket matches right now.':mode==='upcoming'?'No upcoming matches found in the next few days.':'No recent results found.';list.innerHTML=`<div class="empty"><b>${msg}</b><div style="margin-top:7px">Check another tab for more matches.</div></div>`;return}list.innerHTML=items.map(m=>`<div class="match" data-id="${esc(m.id)}"><div class="matchTop"><div><div class="league">${esc(m.league?.name||'Cricket')}</div><div class="format">${esc(m.format||'')}</div></div>${mode==='live'?'<div class="liveTag">● LIVE</div>':`<div class="stateTag ${mode==='results'?'resultTag':''}">${esc(m.state||fmtTime(m.startTime)||'')}</div>`}</div><div class="matchBody">${teamLine(m.home,m.homeScore,m.homeInfo)}${teamLine(m.away,m.awayScore,m.awayInfo)}</div><div class="matchFoot"><div class="report">${esc(m.report||fmtTime(m.startTime)||m.state||'Tap to view match')}</div><div class="go">›</div></div></div>`).join('');list.querySelectorAll('.match').forEach(x=>x.addEventListener('click',()=>openMatch(x.dataset.id)))}
async function loadMode(mode){currentMode=mode;document.querySelectorAll('.modeTab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.getElementById('sectionTitle').textContent=mode==='live'?'Live Matches':mode==='upcoming'?'Upcoming Matches':'Results';const list=document.getElementById('list');loading(list);document.getElementById('status').textContent='Refreshing…';try{const j=await api({action:'matches',mode});renderMatches(j.matches||[],mode);document.getElementById('status').textContent=`${(j.matches||[]).length} match${(j.matches||[]).length===1?'':'es'} · updated ${new Date(j.generatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}catch(e){list.innerHTML=`<div class="error"><b>Cricket feed unavailable</b><br><br>${esc(e.message)}</div>`;document.getElementById('status').textContent='Feed error'}}
document.querySelectorAll('.modeTab').forEach(b=>b.addEventListener('click',()=>loadMode(b.dataset.mode)));
async function openMatch(id){document.getElementById('home').style.display='none';const d=document.getElementById('detail');d.style.display='block';loading(d);try{const j=await api({action:'match',id});currentDetail=j.detail;currentTab='live';renderDetail()}catch(e){d.innerHTML=`<div class="backRow"><button class="back" onclick="backHome()">← Match Center</button></div><div class="error"><b>Could not load match</b><br><br>${esc(e.message)}</div>`}}
function backHome(){document.getElementById('detail').style.display='none';document.getElementById('home').style.display='block'}
function tabs(){return ['live','scorecard','commentary','stats','info'].map(x=>`<button class="detailTab ${currentTab===x?'active':''}" data-tab="${x}">${x.toUpperCase()}</button>`).join('')}
function renderDetail(){const d=document.getElementById('detail'),m=currentDetail.match||{};d.innerHTML=`<div class="backRow"><button class="back" onclick="backHome()">← Match Center</button>${String(m.state||'').toLowerCase().includes('play')?'<span class="detailLive">● LIVE</span>':''}</div><div class="scoreCard"><div class="scoreMeta"><div class="scoreLeague">${esc(m.league?.name||'Cricket')} ${m.format?'· '+esc(m.format):''}</div><div class="scoreState">${esc(m.state||'')}</div></div><div class="versus"><div class="side">${logo(m.home,'sideLogo')}<div class="sideName">${esc(m.home?.name||'Home')}</div><div class="sideScore">${n(m.homeScore)}</div><div class="sideInfo">${esc(m.homeInfo||'')}</div></div><div class="vs">VS</div><div class="side">${logo(m.away,'sideLogo')}<div class="sideName">${esc(m.away?.name||'Away')}</div><div class="sideScore">${n(m.awayScore)}</div><div class="sideInfo">${esc(m.awayInfo||'')}</div></div></div><div class="result">${esc(m.report||fmtTime(m.startTime)||m.state||'')}</div></div><div class="detailTabs">${tabs()}</div><div id="panel" class="panel"></div>`;d.querySelectorAll('.detailTab').forEach(b=>b.addEventListener('click',()=>{currentTab=b.dataset.tab;renderDetail()}));renderPanel()}
function playerName(o){return o?.player?.name||o?.name||'Player'}
function renderPanel(){const p=document.getElementById('panel'),x=currentDetail||{},m=x.match||{};if(currentTab==='live'){const bats=x.inplayData?.batsmen||[],bowls=x.inplayData?.bowlers||[];const cards=[...bats.slice(0,2).map(v=>`<div class="mini"><b>🏏 ${esc(playerName(v))}</b><span>${n(v.player?.statistics?.runs)} runs · ${n(v.player?.statistics?.balls)} balls · SR ${n(v.player?.statistics?.strikeRate)}</span></div>`),...bowls.slice(0,1).map(v=>`<div class="mini"><b>🎯 ${esc(playerName(v))}</b><span>${n(v.player?.statistics?.overs)} ov · ${n(v.player?.statistics?.wickets)} wkts · Econ ${n(v.player?.statistics?.economy)}</span></div>`)].join('');p.innerHTML=`<div class="panelTitle"><b>Live Match</b></div><div class="notice"><b>${esc(m.state||'Match status')}</b><br>${esc(m.report||'Live score updates are coming from the connected cricket feed.')}</div><div class="liveGrid">${cards||'<div class="mini"><b>Live player data</b><span>Waiting for in-play player data.</span></div>'}</div>`}else if(currentTab==='scorecard'){p.innerHTML='<div class="panelTitle"><b>Scorecard</b></div>'+scorecardHtml(x.statistics||[])}else if(currentTab==='commentary'){const tl=x.timeline||[],source=x.timelineSource?`<span class="sourceTag">${esc(x.timelineSource)}</span>`:'';p.innerHTML=`<div class="panelTitle"><b>Ball-by-ball</b>${source}</div>`+(tl.length?tl.slice().reverse().map((e,i)=>`<div class="ballRow"><div class="ballNo">${esc(e.over||e.ball||e.time||('#'+(i+1)))}</div><div class="ballText"><strong>${e.wicket?'WICKET · ':''}</strong>${esc(e.commentary||e.description||e.text||e.event||JSON.stringify(e).slice(0,220))}</div></div>`).join(''):'<div class="notice">Ball-by-ball commentary is not available for this match yet.</div>')}else if(currentTab==='stats'){p.innerHTML='<div class="panelTitle"><b>Match Stats</b></div>'+statsHtml(x.statistics||[])}else{const v=x.venue||{},f=x.forecast||{};p.innerHTML=`<div class="panelTitle"><b>Match Info</b></div><div class="pillrow"><span class="statPill">${esc(m.format||'Cricket')}</span><span class="statPill">${esc(m.state||'')}</span><span class="statPill">${esc(m.league?.name||'')}</span></div><div class="notice"><b>Venue</b><br>${esc(v.name||'—')}${v.city?' · '+esc(v.city):''}${v.country?' · '+esc(v.country):''}</div><div class="notice"><b>Weather</b><br>${esc(f.status||'—')}${f.temperature?' · '+esc(f.temperature):''}</div>`}}
function scorecardHtml(stats){if(!stats.length)return '<div class="notice">Scorecard data is not available for this match yet.</div>';return stats.map((inn,i)=>{const bats=inn.inningBatsmen||[],bowl=inn.inningBowlers||[];return `<div class="innings"><div class="innTitle"><span>${esc(inn.name||inn.abbreviation||('Innings '+(inn.inningNumber||i+1)))}</span><span>${n(inn.inningNumber?'#'+inn.inningNumber:'')}</span></div><div class="tableWrap"><table class="table"><thead><tr><th>BATTER</th><th>R</th><th>B</th><th>4</th><th>6</th><th>SR</th></tr></thead><tbody>${bats.map(b=>`<tr><td>${esc(playerName(b))}</td><td>${n(b.runs)}</td><td>${n(b.balls)}</td><td>${n(b.fours)}</td><td>${n(b.sixes)}</td><td>${n(b.battingStrikeRate)}</td></tr>`).join('')}</tbody></table></div><div class="tableWrap"><table class="table"><thead><tr><th>BOWLER</th><th>O</th><th>R</th><th>W</th><th>ECON</th></tr></thead><tbody>${bowl.map(b=>`<tr><td>${esc(playerName(b))}</td><td>${n(b.overs)}</td><td>${n(b.concededRuns??b.runsConceded)}</td><td>${n(b.wickets)}</td><td>${n(b.economy)}</td></tr>`).join('')}</tbody></table></div></div>`}).join('')}
function statsHtml(stats){if(!stats.length)return '<div class="notice">Detailed innings statistics are not available for this match yet.</div>';return stats.map((inn,i)=>`<div class="innings"><div class="innTitle"><span>${esc(inn.name||inn.abbreviation||('Innings '+(inn.inningNumber||i+1)))}</span></div><div class="pillrow"><span class="statPill">4s: ${n(inn.fours)}</span><span class="statPill">6s: ${n(inn.sixes)}</span><span class="statPill">Extras: ${n(inn.extras)}</span><span class="statPill">Wides: ${n(inn.wides)}</span><span class="statPill">No-balls: ${n(inn.noBalls)}</span></div>${(inn.inningPartnerships||[]).slice(-3).reverse().map(q=>`<div class="notice"><b>Partnership</b> · ${n(q.runs)} runs / ${n(q.balls)} balls<br>${esc(q.firstPlayer?.name||'')} + ${esc(q.secondPlayer?.name||'')}</div>`).join('')}</div>`).join('')}
loadMode('live');
</script>
</body></html>'''


liveline.admin_url = _exact_admin_url
liveline._page = _exact_page

import ibetin_admin_fix_start as app

if __name__ == "__main__":
    app.base.ibetin_start.main()
